//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence.consumer.v2_3.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.presence.consumer.v2_3.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndPresenceNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "endPresenceNotificationResponse");
    private final static QName _StartPresenceNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "startPresenceNotificationResponse");
    private final static QName _EndPresenceNotification_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "endPresenceNotification");
    private final static QName _StartPresenceNotification_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "startPresenceNotification");
    private final static QName _SubscribePresenceResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "subscribePresenceResponse");
    private final static QName _GetUserPresence_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "getUserPresence");
    private final static QName _SubscribePresence_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "subscribePresence");
    private final static QName _GetUserPresenceResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", "getUserPresenceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.presence.consumer.v2_3.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserPresenceResponse }
     * 
     */
    public GetUserPresenceResponse createGetUserPresenceResponse() {
        return new GetUserPresenceResponse();
    }

    /**
     * Create an instance of {@link SubscribePresence }
     * 
     */
    public SubscribePresence createSubscribePresence() {
        return new SubscribePresence();
    }

    /**
     * Create an instance of {@link EndPresenceNotification }
     * 
     */
    public EndPresenceNotification createEndPresenceNotification() {
        return new EndPresenceNotification();
    }

    /**
     * Create an instance of {@link EndPresenceNotificationResponse }
     * 
     */
    public EndPresenceNotificationResponse createEndPresenceNotificationResponse() {
        return new EndPresenceNotificationResponse();
    }

    /**
     * Create an instance of {@link SubscribePresenceResponse }
     * 
     */
    public SubscribePresenceResponse createSubscribePresenceResponse() {
        return new SubscribePresenceResponse();
    }

    /**
     * Create an instance of {@link GetUserPresence }
     * 
     */
    public GetUserPresence createGetUserPresence() {
        return new GetUserPresence();
    }

    /**
     * Create an instance of {@link StartPresenceNotificationResponse }
     * 
     */
    public StartPresenceNotificationResponse createStartPresenceNotificationResponse() {
        return new StartPresenceNotificationResponse();
    }

    /**
     * Create an instance of {@link StartPresenceNotification }
     * 
     */
    public StartPresenceNotification createStartPresenceNotification() {
        return new StartPresenceNotification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndPresenceNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "endPresenceNotificationResponse")
    public JAXBElement<EndPresenceNotificationResponse> createEndPresenceNotificationResponse(EndPresenceNotificationResponse value) {
        return new JAXBElement<EndPresenceNotificationResponse>(_EndPresenceNotificationResponse_QNAME, EndPresenceNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartPresenceNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "startPresenceNotificationResponse")
    public JAXBElement<StartPresenceNotificationResponse> createStartPresenceNotificationResponse(StartPresenceNotificationResponse value) {
        return new JAXBElement<StartPresenceNotificationResponse>(_StartPresenceNotificationResponse_QNAME, StartPresenceNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndPresenceNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "endPresenceNotification")
    public JAXBElement<EndPresenceNotification> createEndPresenceNotification(EndPresenceNotification value) {
        return new JAXBElement<EndPresenceNotification>(_EndPresenceNotification_QNAME, EndPresenceNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartPresenceNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "startPresenceNotification")
    public JAXBElement<StartPresenceNotification> createStartPresenceNotification(StartPresenceNotification value) {
        return new JAXBElement<StartPresenceNotification>(_StartPresenceNotification_QNAME, StartPresenceNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscribePresenceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "subscribePresenceResponse")
    public JAXBElement<SubscribePresenceResponse> createSubscribePresenceResponse(SubscribePresenceResponse value) {
        return new JAXBElement<SubscribePresenceResponse>(_SubscribePresenceResponse_QNAME, SubscribePresenceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserPresence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "getUserPresence")
    public JAXBElement<GetUserPresence> createGetUserPresence(GetUserPresence value) {
        return new JAXBElement<GetUserPresence>(_GetUserPresence_QNAME, GetUserPresence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscribePresence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "subscribePresence")
    public JAXBElement<SubscribePresence> createSubscribePresence(SubscribePresence value) {
        return new JAXBElement<SubscribePresence>(_SubscribePresence_QNAME, SubscribePresence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserPresenceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence/consumer/v2_3/local", name = "getUserPresenceResponse")
    public JAXBElement<GetUserPresenceResponse> createGetUserPresenceResponse(GetUserPresenceResponse value) {
        return new JAXBElement<GetUserPresenceResponse>(_GetUserPresenceResponse_QNAME, GetUserPresenceResponse.class, null, value);
    }

}
