//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.third_party_call.v3_4.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.third_party_call.v3_4.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MakeCallSessionResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "makeCallSessionResponse");
    private final static QName _GetCallParticipantInformation_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "getCallParticipantInformation");
    private final static QName _GetCallParticipantInformationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "getCallParticipantInformationResponse");
    private final static QName _TransferCallParticipant_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "transferCallParticipant");
    private final static QName _MakeCallSession_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "makeCallSession");
    private final static QName _TransferCallParticipantResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "transferCallParticipantResponse");
    private final static QName _AddCallParticipantResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "addCallParticipantResponse");
    private final static QName _AddCallParticipant_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "addCallParticipant");
    private final static QName _DeleteCallParticipant_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "deleteCallParticipant");
    private final static QName _DeleteCallParticipantResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "deleteCallParticipantResponse");
    private final static QName _GetCallSessionInformationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "getCallSessionInformationResponse");
    private final static QName _EndCallSession_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "endCallSession");
    private final static QName _EndCallSessionResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "endCallSessionResponse");
    private final static QName _GetCallSessionInformation_QNAME = new QName("http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", "getCallSessionInformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.third_party_call.v3_4.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCallSessionInformationResponse }
     * 
     */
    public GetCallSessionInformationResponse createGetCallSessionInformationResponse() {
        return new GetCallSessionInformationResponse();
    }

    /**
     * Create an instance of {@link TransferCallParticipant }
     * 
     */
    public TransferCallParticipant createTransferCallParticipant() {
        return new TransferCallParticipant();
    }

    /**
     * Create an instance of {@link AddCallParticipant }
     * 
     */
    public AddCallParticipant createAddCallParticipant() {
        return new AddCallParticipant();
    }

    /**
     * Create an instance of {@link TransferCallParticipantResponse }
     * 
     */
    public TransferCallParticipantResponse createTransferCallParticipantResponse() {
        return new TransferCallParticipantResponse();
    }

    /**
     * Create an instance of {@link EndCallSession }
     * 
     */
    public EndCallSession createEndCallSession() {
        return new EndCallSession();
    }

    /**
     * Create an instance of {@link GetCallSessionInformation }
     * 
     */
    public GetCallSessionInformation createGetCallSessionInformation() {
        return new GetCallSessionInformation();
    }

    /**
     * Create an instance of {@link GetCallParticipantInformation }
     * 
     */
    public GetCallParticipantInformation createGetCallParticipantInformation() {
        return new GetCallParticipantInformation();
    }

    /**
     * Create an instance of {@link DeleteCallParticipant }
     * 
     */
    public DeleteCallParticipant createDeleteCallParticipant() {
        return new DeleteCallParticipant();
    }

    /**
     * Create an instance of {@link GetCallParticipantInformationResponse }
     * 
     */
    public GetCallParticipantInformationResponse createGetCallParticipantInformationResponse() {
        return new GetCallParticipantInformationResponse();
    }

    /**
     * Create an instance of {@link EndCallSessionResponse }
     * 
     */
    public EndCallSessionResponse createEndCallSessionResponse() {
        return new EndCallSessionResponse();
    }

    /**
     * Create an instance of {@link AddCallParticipantResponse }
     * 
     */
    public AddCallParticipantResponse createAddCallParticipantResponse() {
        return new AddCallParticipantResponse();
    }

    /**
     * Create an instance of {@link MakeCallSession }
     * 
     */
    public MakeCallSession createMakeCallSession() {
        return new MakeCallSession();
    }

    /**
     * Create an instance of {@link MakeCallSessionResponse }
     * 
     */
    public MakeCallSessionResponse createMakeCallSessionResponse() {
        return new MakeCallSessionResponse();
    }

    /**
     * Create an instance of {@link DeleteCallParticipantResponse }
     * 
     */
    public DeleteCallParticipantResponse createDeleteCallParticipantResponse() {
        return new DeleteCallParticipantResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MakeCallSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "makeCallSessionResponse")
    public JAXBElement<MakeCallSessionResponse> createMakeCallSessionResponse(MakeCallSessionResponse value) {
        return new JAXBElement<MakeCallSessionResponse>(_MakeCallSessionResponse_QNAME, MakeCallSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCallParticipantInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "getCallParticipantInformation")
    public JAXBElement<GetCallParticipantInformation> createGetCallParticipantInformation(GetCallParticipantInformation value) {
        return new JAXBElement<GetCallParticipantInformation>(_GetCallParticipantInformation_QNAME, GetCallParticipantInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCallParticipantInformationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "getCallParticipantInformationResponse")
    public JAXBElement<GetCallParticipantInformationResponse> createGetCallParticipantInformationResponse(GetCallParticipantInformationResponse value) {
        return new JAXBElement<GetCallParticipantInformationResponse>(_GetCallParticipantInformationResponse_QNAME, GetCallParticipantInformationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransferCallParticipant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "transferCallParticipant")
    public JAXBElement<TransferCallParticipant> createTransferCallParticipant(TransferCallParticipant value) {
        return new JAXBElement<TransferCallParticipant>(_TransferCallParticipant_QNAME, TransferCallParticipant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MakeCallSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "makeCallSession")
    public JAXBElement<MakeCallSession> createMakeCallSession(MakeCallSession value) {
        return new JAXBElement<MakeCallSession>(_MakeCallSession_QNAME, MakeCallSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransferCallParticipantResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "transferCallParticipantResponse")
    public JAXBElement<TransferCallParticipantResponse> createTransferCallParticipantResponse(TransferCallParticipantResponse value) {
        return new JAXBElement<TransferCallParticipantResponse>(_TransferCallParticipantResponse_QNAME, TransferCallParticipantResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddCallParticipantResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "addCallParticipantResponse")
    public JAXBElement<AddCallParticipantResponse> createAddCallParticipantResponse(AddCallParticipantResponse value) {
        return new JAXBElement<AddCallParticipantResponse>(_AddCallParticipantResponse_QNAME, AddCallParticipantResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddCallParticipant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "addCallParticipant")
    public JAXBElement<AddCallParticipant> createAddCallParticipant(AddCallParticipant value) {
        return new JAXBElement<AddCallParticipant>(_AddCallParticipant_QNAME, AddCallParticipant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteCallParticipant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "deleteCallParticipant")
    public JAXBElement<DeleteCallParticipant> createDeleteCallParticipant(DeleteCallParticipant value) {
        return new JAXBElement<DeleteCallParticipant>(_DeleteCallParticipant_QNAME, DeleteCallParticipant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteCallParticipantResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "deleteCallParticipantResponse")
    public JAXBElement<DeleteCallParticipantResponse> createDeleteCallParticipantResponse(DeleteCallParticipantResponse value) {
        return new JAXBElement<DeleteCallParticipantResponse>(_DeleteCallParticipantResponse_QNAME, DeleteCallParticipantResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCallSessionInformationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "getCallSessionInformationResponse")
    public JAXBElement<GetCallSessionInformationResponse> createGetCallSessionInformationResponse(GetCallSessionInformationResponse value) {
        return new JAXBElement<GetCallSessionInformationResponse>(_GetCallSessionInformationResponse_QNAME, GetCallSessionInformationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndCallSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "endCallSession")
    public JAXBElement<EndCallSession> createEndCallSession(EndCallSession value) {
        return new JAXBElement<EndCallSession>(_EndCallSession_QNAME, EndCallSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndCallSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "endCallSessionResponse")
    public JAXBElement<EndCallSessionResponse> createEndCallSessionResponse(EndCallSessionResponse value) {
        return new JAXBElement<EndCallSessionResponse>(_EndCallSessionResponse_QNAME, EndCallSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCallSessionInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/third_party_call/v3_4/local", name = "getCallSessionInformation")
    public JAXBElement<GetCallSessionInformation> createGetCallSessionInformation(GetCallSessionInformation value) {
        return new JAXBElement<GetCallSessionInformation>(_GetCallSessionInformation_QNAME, GetCallSessionInformation.class, null, value);
    }

}
