//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.multimedia_messaging.v3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScheduledDeliveryInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScheduledDeliveryInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deliveryStatus" type="{http://www.csapi.org/schema/parlayx/multimedia_messaging/v3_0}ScheduledDeliveryStatus"/>
 *         &lt;element name="numberOfMessagesSent" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduledDeliveryInformation", propOrder = {
    "deliveryStatus",
    "numberOfMessagesSent"
})
public class ScheduledDeliveryInformation {

    @XmlElement(required = true)
    protected ScheduledDeliveryStatus deliveryStatus;
    protected Integer numberOfMessagesSent;

    /**
     * Gets the value of the deliveryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledDeliveryStatus }
     *     
     */
    public ScheduledDeliveryStatus getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * Sets the value of the deliveryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledDeliveryStatus }
     *     
     */
    public void setDeliveryStatus(ScheduledDeliveryStatus value) {
        this.deliveryStatus = value;
    }

    /**
     * Gets the value of the numberOfMessagesSent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfMessagesSent() {
        return numberOfMessagesSent;
    }

    /**
     * Sets the value of the numberOfMessagesSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfMessagesSent(Integer value) {
        this.numberOfMessagesSent = value;
    }

}
