//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.audio_call.v3_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.csapi.schema.parlayx.common.v3_1.TimeMetric;


/**
 * <p>Java class for RecConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recFileLocation" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="maxRecordingLength" type="{http://www.csapi.org/schema/parlayx/common/v3_1}TimeMetric" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecConfig", propOrder = {
    "recFileLocation",
    "maxRecordingLength"
})
public class RecConfig {

    @XmlSchemaType(name = "anyURI")
    protected String recFileLocation;
    protected TimeMetric maxRecordingLength;

    /**
     * Gets the value of the recFileLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecFileLocation() {
        return recFileLocation;
    }

    /**
     * Sets the value of the recFileLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecFileLocation(String value) {
        this.recFileLocation = value;
    }

    /**
     * Gets the value of the maxRecordingLength property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetric }
     *     
     */
    public TimeMetric getMaxRecordingLength() {
        return maxRecordingLength;
    }

    /**
     * Sets the value of the maxRecordingLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetric }
     *     
     */
    public void setMaxRecordingLength(TimeMetric value) {
        this.maxRecordingLength = value;
    }

}
