//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package com.nortel.xmlprotocol.wsdl.communications.services.callforwarding.v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conditionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="conditionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="forwardBusy"/>
 *     &lt;enumeration value="forwardNoAns"/>
 *     &lt;enumeration value="forwardImmediate"/>
 *     &lt;enumeration value="forwardDoNotDisturb"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "conditionType")
@XmlEnum
public enum ConditionType {

    @XmlEnumValue("forwardBusy")
    FORWARD_BUSY("forwardBusy"),
    @XmlEnumValue("forwardNoAns")
    FORWARD_NO_ANS("forwardNoAns"),
    @XmlEnumValue("forwardImmediate")
    FORWARD_IMMEDIATE("forwardImmediate"),
    @XmlEnumValue("forwardDoNotDisturb")
    FORWARD_DO_NOT_DISTURB("forwardDoNotDisturb");
    private final String value;

    ConditionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConditionType fromValue(String v) {
        for (ConditionType c: ConditionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
