//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package com.nortel.xmlprotocol.wsdl.communications.services.callforwarding.v1_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instructionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instructionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="forwardingAddress" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="activeForwarding" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="condition" type="{http://www.nortel.com/xmlprotocol/wsdl/communications/services/callforwarding/v1_0/}conditionType" minOccurs="0"/>
 *         &lt;element name="incomingFilter" type="{http://www.nortel.com/xmlprotocol/wsdl/communications/services/callforwarding/v1_0/}incomingFilterType" minOccurs="0"/>
 *         &lt;element name="ringCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ringDuration" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="specificCaller" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instructionType", propOrder = {
    "forwardingAddress",
    "activeForwarding",
    "condition",
    "incomingFilter",
    "ringCount",
    "ringDuration",
    "specificCaller"
})
public class InstructionType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String forwardingAddress;
    @XmlElement(defaultValue = "true")
    protected Boolean activeForwarding;
    @XmlElement(defaultValue = "forwardImmediate")
    protected ConditionType condition;
    @XmlElement(defaultValue = "AllCalls")
    protected IncomingFilterType incomingFilter;
    protected BigInteger ringCount;
    protected BigInteger ringDuration;
    @XmlSchemaType(name = "anyURI")
    protected List<String> specificCaller;

    /**
     * Gets the value of the forwardingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingAddress() {
        return forwardingAddress;
    }

    /**
     * Sets the value of the forwardingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingAddress(String value) {
        this.forwardingAddress = value;
    }

    /**
     * Gets the value of the activeForwarding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActiveForwarding() {
        return activeForwarding;
    }

    /**
     * Sets the value of the activeForwarding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActiveForwarding(Boolean value) {
        this.activeForwarding = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionType }
     *     
     */
    public ConditionType getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionType }
     *     
     */
    public void setCondition(ConditionType value) {
        this.condition = value;
    }

    /**
     * Gets the value of the incomingFilter property.
     * 
     * @return
     *     possible object is
     *     {@link IncomingFilterType }
     *     
     */
    public IncomingFilterType getIncomingFilter() {
        return incomingFilter;
    }

    /**
     * Sets the value of the incomingFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncomingFilterType }
     *     
     */
    public void setIncomingFilter(IncomingFilterType value) {
        this.incomingFilter = value;
    }

    /**
     * Gets the value of the ringCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRingCount() {
        return ringCount;
    }

    /**
     * Sets the value of the ringCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRingCount(BigInteger value) {
        this.ringCount = value;
    }

    /**
     * Gets the value of the ringDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRingDuration() {
        return ringDuration;
    }

    /**
     * Sets the value of the ringDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRingDuration(BigInteger value) {
        this.ringDuration = value;
    }

    /**
     * Gets the value of the specificCaller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specificCaller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecificCaller().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecificCaller() {
        if (specificCaller == null) {
            specificCaller = new ArrayList<String>();
        }
        return this.specificCaller;
    }

}
