//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence_supplier.notification.v3_0.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.presence_supplier.notification.v3_0.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotifyOpenSubscription_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", "notifyOpenSubscription");
    private final static QName _NotifyEndResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", "notifyEndResponse");
    private final static QName _NotifyEnd_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", "notifyEnd");
    private final static QName _NotifyError_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", "notifyError");
    private final static QName _NotifyErrorResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", "notifyErrorResponse");
    private final static QName _NotifyOpenSubscriptionResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", "notifyOpenSubscriptionResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.presence_supplier.notification.v3_0.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifyError }
     * 
     */
    public NotifyError createNotifyError() {
        return new NotifyError();
    }

    /**
     * Create an instance of {@link NotifyEnd }
     * 
     */
    public NotifyEnd createNotifyEnd() {
        return new NotifyEnd();
    }

    /**
     * Create an instance of {@link NotifyErrorResponse }
     * 
     */
    public NotifyErrorResponse createNotifyErrorResponse() {
        return new NotifyErrorResponse();
    }

    /**
     * Create an instance of {@link NotifyOpenSubscription }
     * 
     */
    public NotifyOpenSubscription createNotifyOpenSubscription() {
        return new NotifyOpenSubscription();
    }

    /**
     * Create an instance of {@link NotifyEndResponse }
     * 
     */
    public NotifyEndResponse createNotifyEndResponse() {
        return new NotifyEndResponse();
    }

    /**
     * Create an instance of {@link NotifyOpenSubscriptionResponse }
     * 
     */
    public NotifyOpenSubscriptionResponse createNotifyOpenSubscriptionResponse() {
        return new NotifyOpenSubscriptionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyOpenSubscription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", name = "notifyOpenSubscription")
    public JAXBElement<NotifyOpenSubscription> createNotifyOpenSubscription(NotifyOpenSubscription value) {
        return new JAXBElement<NotifyOpenSubscription>(_NotifyOpenSubscription_QNAME, NotifyOpenSubscription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyEndResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", name = "notifyEndResponse")
    public JAXBElement<NotifyEndResponse> createNotifyEndResponse(NotifyEndResponse value) {
        return new JAXBElement<NotifyEndResponse>(_NotifyEndResponse_QNAME, NotifyEndResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyEnd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", name = "notifyEnd")
    public JAXBElement<NotifyEnd> createNotifyEnd(NotifyEnd value) {
        return new JAXBElement<NotifyEnd>(_NotifyEnd_QNAME, NotifyEnd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyError }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", name = "notifyError")
    public JAXBElement<NotifyError> createNotifyError(NotifyError value) {
        return new JAXBElement<NotifyError>(_NotifyError_QNAME, NotifyError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyErrorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", name = "notifyErrorResponse")
    public JAXBElement<NotifyErrorResponse> createNotifyErrorResponse(NotifyErrorResponse value) {
        return new JAXBElement<NotifyErrorResponse>(_NotifyErrorResponse_QNAME, NotifyErrorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyOpenSubscriptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/presence_supplier/notification/v3_0/local", name = "notifyOpenSubscriptionResponse")
    public JAXBElement<NotifyOpenSubscriptionResponse> createNotifyOpenSubscriptionResponse(NotifyOpenSubscriptionResponse value) {
        return new JAXBElement<NotifyOpenSubscriptionResponse>(_NotifyOpenSubscriptionResponse_QNAME, NotifyOpenSubscriptionResponse.class, null, value);
    }

}
