//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.terminal_location.notification_manager.v2_3.local;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.csapi.schema.parlayx.common.v2_1.SimpleReference;
import org.csapi.schema.parlayx.common.v2_1.TimeMetric;
import org.csapi.schema.parlayx.terminal_location.v2_2.EnteringLeavingCriteria;


/**
 * <p>Java class for startGeographicalNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="startGeographicalNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference" type="{http://www.csapi.org/schema/parlayx/common/v2_1}SimpleReference"/>
 *         &lt;element name="addresses" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="radius" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="trackingAccuracy" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="criteria" type="{http://www.csapi.org/schema/parlayx/terminal_location/v2_2}EnteringLeavingCriteria"/>
 *         &lt;element name="checkImmediate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="frequency" type="{http://www.csapi.org/schema/parlayx/common/v2_1}TimeMetric"/>
 *         &lt;element name="duration" type="{http://www.csapi.org/schema/parlayx/common/v2_1}TimeMetric" minOccurs="0"/>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "startGeographicalNotification", propOrder = {
    "reference",
    "addresses",
    "latitude",
    "longitude",
    "radius",
    "trackingAccuracy",
    "criteria",
    "checkImmediate",
    "frequency",
    "duration",
    "count"
})
public class StartGeographicalNotification {

    @XmlElement(required = true)
    protected SimpleReference reference;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected List<String> addresses;
    protected float latitude;
    protected float longitude;
    protected float radius;
    protected float trackingAccuracy;
    @XmlElement(required = true)
    protected EnteringLeavingCriteria criteria;
    protected boolean checkImmediate;
    @XmlElement(required = true)
    protected TimeMetric frequency;
    protected TimeMetric duration;
    protected Integer count;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleReference }
     *     
     */
    public SimpleReference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleReference }
     *     
     */
    public void setReference(SimpleReference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAddresses() {
        if (addresses == null) {
            addresses = new ArrayList<String>();
        }
        return this.addresses;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public float getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(float value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public float getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     */
    public float getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     */
    public void setRadius(float value) {
        this.radius = value;
    }

    /**
     * Gets the value of the trackingAccuracy property.
     * 
     */
    public float getTrackingAccuracy() {
        return trackingAccuracy;
    }

    /**
     * Sets the value of the trackingAccuracy property.
     * 
     */
    public void setTrackingAccuracy(float value) {
        this.trackingAccuracy = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link EnteringLeavingCriteria }
     *     
     */
    public EnteringLeavingCriteria getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteringLeavingCriteria }
     *     
     */
    public void setCriteria(EnteringLeavingCriteria value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the checkImmediate property.
     * 
     */
    public boolean isCheckImmediate() {
        return checkImmediate;
    }

    /**
     * Sets the value of the checkImmediate property.
     * 
     */
    public void setCheckImmediate(boolean value) {
        this.checkImmediate = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetric }
     *     
     */
    public TimeMetric getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetric }
     *     
     */
    public void setFrequency(TimeMetric value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetric }
     *     
     */
    public TimeMetric getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetric }
     *     
     */
    public void setDuration(TimeMetric value) {
        this.duration = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

}
