//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.multimedia_messaging.notification.v3_1.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.multimedia_messaging.notification.v3_1.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotifyMessageReceptionResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", "notifyMessageReceptionResponse");
    private final static QName _NotifyMessageDeliveryReceipt_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", "notifyMessageDeliveryReceipt");
    private final static QName _NotifyMessageReception_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", "notifyMessageReception");
    private final static QName _NotifyMessageDeliveryReceiptResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", "notifyMessageDeliveryReceiptResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.multimedia_messaging.notification.v3_1.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifyMessageReceptionResponse }
     * 
     */
    public NotifyMessageReceptionResponse createNotifyMessageReceptionResponse() {
        return new NotifyMessageReceptionResponse();
    }

    /**
     * Create an instance of {@link NotifyMessageDeliveryReceipt }
     * 
     */
    public NotifyMessageDeliveryReceipt createNotifyMessageDeliveryReceipt() {
        return new NotifyMessageDeliveryReceipt();
    }

    /**
     * Create an instance of {@link NotifyMessageDeliveryReceiptResponse }
     * 
     */
    public NotifyMessageDeliveryReceiptResponse createNotifyMessageDeliveryReceiptResponse() {
        return new NotifyMessageDeliveryReceiptResponse();
    }

    /**
     * Create an instance of {@link NotifyMessageReception }
     * 
     */
    public NotifyMessageReception createNotifyMessageReception() {
        return new NotifyMessageReception();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyMessageReceptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", name = "notifyMessageReceptionResponse")
    public JAXBElement<NotifyMessageReceptionResponse> createNotifyMessageReceptionResponse(NotifyMessageReceptionResponse value) {
        return new JAXBElement<NotifyMessageReceptionResponse>(_NotifyMessageReceptionResponse_QNAME, NotifyMessageReceptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyMessageDeliveryReceipt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", name = "notifyMessageDeliveryReceipt")
    public JAXBElement<NotifyMessageDeliveryReceipt> createNotifyMessageDeliveryReceipt(NotifyMessageDeliveryReceipt value) {
        return new JAXBElement<NotifyMessageDeliveryReceipt>(_NotifyMessageDeliveryReceipt_QNAME, NotifyMessageDeliveryReceipt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyMessageReception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", name = "notifyMessageReception")
    public JAXBElement<NotifyMessageReception> createNotifyMessageReception(NotifyMessageReception value) {
        return new JAXBElement<NotifyMessageReception>(_NotifyMessageReception_QNAME, NotifyMessageReception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyMessageDeliveryReceiptResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/notification/v3_1/local", name = "notifyMessageDeliveryReceiptResponse")
    public JAXBElement<NotifyMessageDeliveryReceiptResponse> createNotifyMessageDeliveryReceiptResponse(NotifyMessageDeliveryReceiptResponse value) {
        return new JAXBElement<NotifyMessageDeliveryReceiptResponse>(_NotifyMessageDeliveryReceiptResponse_QNAME, NotifyMessageDeliveryReceiptResponse.class, null, value);
    }

}
