//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.multimedia_messaging.receive.v3_1.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.multimedia_messaging.receive.v3_1.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetMessageURIs_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", "getMessageURIs");
    private final static QName _GetReceivedMessages_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", "getReceivedMessages");
    private final static QName _GetMessageURIsResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", "getMessageURIsResponse");
    private final static QName _GetReceivedMessagesResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", "getReceivedMessagesResponse");
    private final static QName _GetMessageResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", "getMessageResponse");
    private final static QName _GetMessage_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", "getMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.multimedia_messaging.receive.v3_1.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMessageURIs }
     * 
     */
    public GetMessageURIs createGetMessageURIs() {
        return new GetMessageURIs();
    }

    /**
     * Create an instance of {@link GetReceivedMessagesResponse }
     * 
     */
    public GetReceivedMessagesResponse createGetReceivedMessagesResponse() {
        return new GetReceivedMessagesResponse();
    }

    /**
     * Create an instance of {@link GetReceivedMessages }
     * 
     */
    public GetReceivedMessages createGetReceivedMessages() {
        return new GetReceivedMessages();
    }

    /**
     * Create an instance of {@link GetMessage }
     * 
     */
    public GetMessage createGetMessage() {
        return new GetMessage();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link GetMessageURIsResponse }
     * 
     */
    public GetMessageURIsResponse createGetMessageURIsResponse() {
        return new GetMessageURIsResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageURIs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", name = "getMessageURIs")
    public JAXBElement<GetMessageURIs> createGetMessageURIs(GetMessageURIs value) {
        return new JAXBElement<GetMessageURIs>(_GetMessageURIs_QNAME, GetMessageURIs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReceivedMessages }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", name = "getReceivedMessages")
    public JAXBElement<GetReceivedMessages> createGetReceivedMessages(GetReceivedMessages value) {
        return new JAXBElement<GetReceivedMessages>(_GetReceivedMessages_QNAME, GetReceivedMessages.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageURIsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", name = "getMessageURIsResponse")
    public JAXBElement<GetMessageURIsResponse> createGetMessageURIsResponse(GetMessageURIsResponse value) {
        return new JAXBElement<GetMessageURIsResponse>(_GetMessageURIsResponse_QNAME, GetMessageURIsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReceivedMessagesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", name = "getReceivedMessagesResponse")
    public JAXBElement<GetReceivedMessagesResponse> createGetReceivedMessagesResponse(GetReceivedMessagesResponse value) {
        return new JAXBElement<GetReceivedMessagesResponse>(_GetReceivedMessagesResponse_QNAME, GetReceivedMessagesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", name = "getMessageResponse")
    public JAXBElement<GetMessageResponse> createGetMessageResponse(GetMessageResponse value) {
        return new JAXBElement<GetMessageResponse>(_GetMessageResponse_QNAME, GetMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/receive/v3_1/local", name = "getMessage")
    public JAXBElement<GetMessage> createGetMessage(GetMessage value) {
        return new JAXBElement<GetMessage>(_GetMessage_QNAME, GetMessage.class, null, value);
    }

}
