//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.multimedia_conference.v3_0.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.multimedia_conference.v3_0.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetParticipantInfoResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "getParticipantInfoResponse");
    private final static QName _InviteParticipant_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "inviteParticipant");
    private final static QName _GetConferenceInfoResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "getConferenceInfoResponse");
    private final static QName _InviteParticipantResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "inviteParticipantResponse");
    private final static QName _GetParticipantInfo_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "getParticipantInfo");
    private final static QName _DisconnectParticipant_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "disconnectParticipant");
    private final static QName _CreateConferenceResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "createConferenceResponse");
    private final static QName _EndConference_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "endConference");
    private final static QName _CreateConference_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "createConference");
    private final static QName _GetParticipantsResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "getParticipantsResponse");
    private final static QName _EndConferenceResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "endConferenceResponse");
    private final static QName _DisconnectParticipantResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "disconnectParticipantResponse");
    private final static QName _GetParticipants_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "getParticipants");
    private final static QName _GetConferenceInfo_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", "getConferenceInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.multimedia_conference.v3_0.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetConferenceInfoResponse }
     * 
     */
    public GetConferenceInfoResponse createGetConferenceInfoResponse() {
        return new GetConferenceInfoResponse();
    }

    /**
     * Create an instance of {@link InviteParticipant }
     * 
     */
    public InviteParticipant createInviteParticipant() {
        return new InviteParticipant();
    }

    /**
     * Create an instance of {@link GetParticipantInfo }
     * 
     */
    public GetParticipantInfo createGetParticipantInfo() {
        return new GetParticipantInfo();
    }

    /**
     * Create an instance of {@link EndConferenceResponse }
     * 
     */
    public EndConferenceResponse createEndConferenceResponse() {
        return new EndConferenceResponse();
    }

    /**
     * Create an instance of {@link CreateConference }
     * 
     */
    public CreateConference createCreateConference() {
        return new CreateConference();
    }

    /**
     * Create an instance of {@link CreateConferenceResponse }
     * 
     */
    public CreateConferenceResponse createCreateConferenceResponse() {
        return new CreateConferenceResponse();
    }

    /**
     * Create an instance of {@link GetConferenceInfo }
     * 
     */
    public GetConferenceInfo createGetConferenceInfo() {
        return new GetConferenceInfo();
    }

    /**
     * Create an instance of {@link InviteParticipantResponse }
     * 
     */
    public InviteParticipantResponse createInviteParticipantResponse() {
        return new InviteParticipantResponse();
    }

    /**
     * Create an instance of {@link EndConference }
     * 
     */
    public EndConference createEndConference() {
        return new EndConference();
    }

    /**
     * Create an instance of {@link GetParticipants }
     * 
     */
    public GetParticipants createGetParticipants() {
        return new GetParticipants();
    }

    /**
     * Create an instance of {@link DisconnectParticipant }
     * 
     */
    public DisconnectParticipant createDisconnectParticipant() {
        return new DisconnectParticipant();
    }

    /**
     * Create an instance of {@link DisconnectParticipantResponse }
     * 
     */
    public DisconnectParticipantResponse createDisconnectParticipantResponse() {
        return new DisconnectParticipantResponse();
    }

    /**
     * Create an instance of {@link GetParticipantInfoResponse }
     * 
     */
    public GetParticipantInfoResponse createGetParticipantInfoResponse() {
        return new GetParticipantInfoResponse();
    }

    /**
     * Create an instance of {@link GetParticipantsResponse }
     * 
     */
    public GetParticipantsResponse createGetParticipantsResponse() {
        return new GetParticipantsResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetParticipantInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "getParticipantInfoResponse")
    public JAXBElement<GetParticipantInfoResponse> createGetParticipantInfoResponse(GetParticipantInfoResponse value) {
        return new JAXBElement<GetParticipantInfoResponse>(_GetParticipantInfoResponse_QNAME, GetParticipantInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InviteParticipant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "inviteParticipant")
    public JAXBElement<InviteParticipant> createInviteParticipant(InviteParticipant value) {
        return new JAXBElement<InviteParticipant>(_InviteParticipant_QNAME, InviteParticipant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConferenceInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "getConferenceInfoResponse")
    public JAXBElement<GetConferenceInfoResponse> createGetConferenceInfoResponse(GetConferenceInfoResponse value) {
        return new JAXBElement<GetConferenceInfoResponse>(_GetConferenceInfoResponse_QNAME, GetConferenceInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InviteParticipantResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "inviteParticipantResponse")
    public JAXBElement<InviteParticipantResponse> createInviteParticipantResponse(InviteParticipantResponse value) {
        return new JAXBElement<InviteParticipantResponse>(_InviteParticipantResponse_QNAME, InviteParticipantResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetParticipantInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "getParticipantInfo")
    public JAXBElement<GetParticipantInfo> createGetParticipantInfo(GetParticipantInfo value) {
        return new JAXBElement<GetParticipantInfo>(_GetParticipantInfo_QNAME, GetParticipantInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisconnectParticipant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "disconnectParticipant")
    public JAXBElement<DisconnectParticipant> createDisconnectParticipant(DisconnectParticipant value) {
        return new JAXBElement<DisconnectParticipant>(_DisconnectParticipant_QNAME, DisconnectParticipant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateConferenceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "createConferenceResponse")
    public JAXBElement<CreateConferenceResponse> createCreateConferenceResponse(CreateConferenceResponse value) {
        return new JAXBElement<CreateConferenceResponse>(_CreateConferenceResponse_QNAME, CreateConferenceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndConference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "endConference")
    public JAXBElement<EndConference> createEndConference(EndConference value) {
        return new JAXBElement<EndConference>(_EndConference_QNAME, EndConference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateConference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "createConference")
    public JAXBElement<CreateConference> createCreateConference(CreateConference value) {
        return new JAXBElement<CreateConference>(_CreateConference_QNAME, CreateConference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetParticipantsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "getParticipantsResponse")
    public JAXBElement<GetParticipantsResponse> createGetParticipantsResponse(GetParticipantsResponse value) {
        return new JAXBElement<GetParticipantsResponse>(_GetParticipantsResponse_QNAME, GetParticipantsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndConferenceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "endConferenceResponse")
    public JAXBElement<EndConferenceResponse> createEndConferenceResponse(EndConferenceResponse value) {
        return new JAXBElement<EndConferenceResponse>(_EndConferenceResponse_QNAME, EndConferenceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisconnectParticipantResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "disconnectParticipantResponse")
    public JAXBElement<DisconnectParticipantResponse> createDisconnectParticipantResponse(DisconnectParticipantResponse value) {
        return new JAXBElement<DisconnectParticipantResponse>(_DisconnectParticipantResponse_QNAME, DisconnectParticipantResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetParticipants }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "getParticipants")
    public JAXBElement<GetParticipants> createGetParticipants(GetParticipants value) {
        return new JAXBElement<GetParticipants>(_GetParticipants_QNAME, GetParticipants.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConferenceInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0/local", name = "getConferenceInfo")
    public JAXBElement<GetConferenceInfo> createGetConferenceInfo(GetConferenceInfo value) {
        return new JAXBElement<GetConferenceInfo>(_GetConferenceInfo_QNAME, GetConferenceInfo.class, null, value);
    }

}
