//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.multimedia_messaging.send.v3_1.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.multimedia_messaging.send.v3_1.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendMessageResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "sendMessageResponse");
    private final static QName _ScheduleMessage_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "scheduleMessage");
    private final static QName _SendMessage_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "sendMessage");
    private final static QName _CancelScheduledMessage_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "cancelScheduledMessage");
    private final static QName _GetMessageDeliveryStatusResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "getMessageDeliveryStatusResponse");
    private final static QName _GetMessageDeliveryStatus_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "getMessageDeliveryStatus");
    private final static QName _GetScheduledMessageStatus_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "getScheduledMessageStatus");
    private final static QName _GetScheduledMessageStatusResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "getScheduledMessageStatusResponse");
    private final static QName _CancelScheduledMessageResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "cancelScheduledMessageResponse");
    private final static QName _ScheduleMessageResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", "scheduleMessageResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.multimedia_messaging.send.v3_1.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelScheduledMessageResponse }
     * 
     */
    public CancelScheduledMessageResponse createCancelScheduledMessageResponse() {
        return new CancelScheduledMessageResponse();
    }

    /**
     * Create an instance of {@link ScheduleMessage }
     * 
     */
    public ScheduleMessage createScheduleMessage() {
        return new ScheduleMessage();
    }

    /**
     * Create an instance of {@link GetScheduledMessageStatusResponse }
     * 
     */
    public GetScheduledMessageStatusResponse createGetScheduledMessageStatusResponse() {
        return new GetScheduledMessageStatusResponse();
    }

    /**
     * Create an instance of {@link ScheduleMessageResponse }
     * 
     */
    public ScheduleMessageResponse createScheduleMessageResponse() {
        return new ScheduleMessageResponse();
    }

    /**
     * Create an instance of {@link GetScheduledMessageStatus }
     * 
     */
    public GetScheduledMessageStatus createGetScheduledMessageStatus() {
        return new GetScheduledMessageStatus();
    }

    /**
     * Create an instance of {@link GetMessageDeliveryStatus }
     * 
     */
    public GetMessageDeliveryStatus createGetMessageDeliveryStatus() {
        return new GetMessageDeliveryStatus();
    }

    /**
     * Create an instance of {@link CancelScheduledMessage }
     * 
     */
    public CancelScheduledMessage createCancelScheduledMessage() {
        return new CancelScheduledMessage();
    }

    /**
     * Create an instance of {@link GetMessageDeliveryStatusResponse }
     * 
     */
    public GetMessageDeliveryStatusResponse createGetMessageDeliveryStatusResponse() {
        return new GetMessageDeliveryStatusResponse();
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "sendMessageResponse")
    public JAXBElement<SendMessageResponse> createSendMessageResponse(SendMessageResponse value) {
        return new JAXBElement<SendMessageResponse>(_SendMessageResponse_QNAME, SendMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScheduleMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "scheduleMessage")
    public JAXBElement<ScheduleMessage> createScheduleMessage(ScheduleMessage value) {
        return new JAXBElement<ScheduleMessage>(_ScheduleMessage_QNAME, ScheduleMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "sendMessage")
    public JAXBElement<SendMessage> createSendMessage(SendMessage value) {
        return new JAXBElement<SendMessage>(_SendMessage_QNAME, SendMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelScheduledMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "cancelScheduledMessage")
    public JAXBElement<CancelScheduledMessage> createCancelScheduledMessage(CancelScheduledMessage value) {
        return new JAXBElement<CancelScheduledMessage>(_CancelScheduledMessage_QNAME, CancelScheduledMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageDeliveryStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "getMessageDeliveryStatusResponse")
    public JAXBElement<GetMessageDeliveryStatusResponse> createGetMessageDeliveryStatusResponse(GetMessageDeliveryStatusResponse value) {
        return new JAXBElement<GetMessageDeliveryStatusResponse>(_GetMessageDeliveryStatusResponse_QNAME, GetMessageDeliveryStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageDeliveryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "getMessageDeliveryStatus")
    public JAXBElement<GetMessageDeliveryStatus> createGetMessageDeliveryStatus(GetMessageDeliveryStatus value) {
        return new JAXBElement<GetMessageDeliveryStatus>(_GetMessageDeliveryStatus_QNAME, GetMessageDeliveryStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetScheduledMessageStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "getScheduledMessageStatus")
    public JAXBElement<GetScheduledMessageStatus> createGetScheduledMessageStatus(GetScheduledMessageStatus value) {
        return new JAXBElement<GetScheduledMessageStatus>(_GetScheduledMessageStatus_QNAME, GetScheduledMessageStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetScheduledMessageStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "getScheduledMessageStatusResponse")
    public JAXBElement<GetScheduledMessageStatusResponse> createGetScheduledMessageStatusResponse(GetScheduledMessageStatusResponse value) {
        return new JAXBElement<GetScheduledMessageStatusResponse>(_GetScheduledMessageStatusResponse_QNAME, GetScheduledMessageStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelScheduledMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "cancelScheduledMessageResponse")
    public JAXBElement<CancelScheduledMessageResponse> createCancelScheduledMessageResponse(CancelScheduledMessageResponse value) {
        return new JAXBElement<CancelScheduledMessageResponse>(_CancelScheduledMessageResponse_QNAME, CancelScheduledMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScheduleMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/multimedia_messaging/send/v3_1/local", name = "scheduleMessageResponse")
    public JAXBElement<ScheduleMessageResponse> createScheduleMessageResponse(ScheduleMessageResponse value) {
        return new JAXBElement<ScheduleMessageResponse>(_ScheduleMessageResponse_QNAME, ScheduleMessageResponse.class, null, value);
    }

}
