<?xml version="1.0" encoding="UTF-8"?>
<!-- March 13, 2007 -->
<wsdl:definitions
   name="presence_supplier_notification_manager_service"
   targetNamespace="http://www.csapi.org/wsdl/parlayx/presence_supplier/notification_manager/v3_0/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/parlayx/presence_supplier/notification_manager/v3_0/service"
   xmlns:interface="http://www.csapi.org/wsdl/parlayx/presence_supplier/notification_manager/v3_0/interface">

   <wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/presence_supplier/notification_manager/v3_0/interface" location="parlayx_presence_supplier_notification_manager_interface_3_0.wsdl"/>

   <wsdl:binding name="PresenceSupplierNotificationManagerBinding" type="interface:PresenceSupplierNotificationManager">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="startSubscriptionNotification">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="endNotification">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="PresenceSupplierNotificationManagerService">
      <wsdl:port name="PresenceSupplierNotificationManager" binding="tns:PresenceSupplierNotificationManagerBinding">
         <soap:address location="http://localhost:9080/PresenceSupplierNotificationManagerService/services/PresenceSupplierNotificationManager"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
