<?xml version="1.0" encoding="UTF-8"?>
<!-- March 8, 2007 -->
<wsdl:definitions
   name="parlayx_mm_notification_service"
   targetNamespace="http://www.csapi.org/wsdl/parlayx/multimedia_messaging/notification/v3_1/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/parlayx/multimedia_messaging/notification/v3_1/service"
   xmlns:interface="http://www.csapi.org/wsdl/parlayx/multimedia_messaging/notification/v3_1/interface">

   <wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/multimedia_messaging/notification/v3_1/interface" location="parlayx_mm_notification_interface_3_1.wsdl"/>

   <wsdl:binding name="MessageNotificationBinding" type="interface:MessageNotification">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="notifyMessageReception">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
      </wsdl:operation>

      <wsdl:operation name="notifyMessageDeliveryReceipt">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="MessageNotificationService">
      <wsdl:port name="MessageNotification" binding="tns:MessageNotificationBinding">
         <soap:address location="http://localhost:9080/MessageNotificationService/services/MessageNotification"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
