<?xml version="1.0" encoding="UTF-8"?>
<!-- January 5, 2006 -->
<wsdl:definitions
   name="terminal_location_service"
   targetNamespace="http://www.csapi.org/wsdl/parlayx/terminal_location/v2_2/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/parlayx/terminal_location/v2_2/service"
   xmlns:interface="http://www.csapi.org/wsdl/parlayx/terminal_location/v2_2/interface">

   <wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/terminal_location/v2_2/interface" location="parlayx_terminal_location_interface_2_2.wsdl"/>

   <wsdl:binding name="TerminalLocationBinding" type="interface:TerminalLocation">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getLocation">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="getTerminalDistance">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="getLocationForGroup">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="TerminalLocationService">
      <wsdl:port name="TerminalLocation" binding="tns:TerminalLocationBinding">
         <soap:address location="http://localhost:9080/TerminalLocationService/services/TerminalLocation"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
