//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence.v2_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlaceValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlaceValue">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PlaceNone"/>
 *     &lt;enumeration value="Home"/>
 *     &lt;enumeration value="Office"/>
 *     &lt;enumeration value="PublicTransport"/>
 *     &lt;enumeration value="Street"/>
 *     &lt;enumeration value="Outdoors"/>
 *     &lt;enumeration value="PublicPlace"/>
 *     &lt;enumeration value="Hotel"/>
 *     &lt;enumeration value="Theatre"/>
 *     &lt;enumeration value="Restaurant"/>
 *     &lt;enumeration value="School"/>
 *     &lt;enumeration value="Industrial"/>
 *     &lt;enumeration value="Quiet"/>
 *     &lt;enumeration value="Noisy"/>
 *     &lt;enumeration value="Aircraft"/>
 *     &lt;enumeration value="Ship"/>
 *     &lt;enumeration value="Bus"/>
 *     &lt;enumeration value="Station"/>
 *     &lt;enumeration value="Mall"/>
 *     &lt;enumeration value="Airport"/>
 *     &lt;enumeration value="Train"/>
 *     &lt;enumeration value="PlaceOther"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlaceValue")
@XmlEnum
public enum PlaceValue {

    @XmlEnumValue("PlaceNone")
    PLACE_NONE("PlaceNone"),
    @XmlEnumValue("Home")
    HOME("Home"),
    @XmlEnumValue("Office")
    OFFICE("Office"),
    @XmlEnumValue("PublicTransport")
    PUBLIC_TRANSPORT("PublicTransport"),
    @XmlEnumValue("Street")
    STREET("Street"),
    @XmlEnumValue("Outdoors")
    OUTDOORS("Outdoors"),
    @XmlEnumValue("PublicPlace")
    PUBLIC_PLACE("PublicPlace"),
    @XmlEnumValue("Hotel")
    HOTEL("Hotel"),
    @XmlEnumValue("Theatre")
    THEATRE("Theatre"),
    @XmlEnumValue("Restaurant")
    RESTAURANT("Restaurant"),
    @XmlEnumValue("School")
    SCHOOL("School"),
    @XmlEnumValue("Industrial")
    INDUSTRIAL("Industrial"),
    @XmlEnumValue("Quiet")
    QUIET("Quiet"),
    @XmlEnumValue("Noisy")
    NOISY("Noisy"),
    @XmlEnumValue("Aircraft")
    AIRCRAFT("Aircraft"),
    @XmlEnumValue("Ship")
    SHIP("Ship"),
    @XmlEnumValue("Bus")
    BUS("Bus"),
    @XmlEnumValue("Station")
    STATION("Station"),
    @XmlEnumValue("Mall")
    MALL("Mall"),
    @XmlEnumValue("Airport")
    AIRPORT("Airport"),
    @XmlEnumValue("Train")
    TRAIN("Train"),
    @XmlEnumValue("PlaceOther")
    PLACE_OTHER("PlaceOther");
    private final String value;

    PlaceValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlaceValue fromValue(String v) {
        for (PlaceValue c: PlaceValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
