//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence.v2_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PresenceAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PresenceAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Activity"/>
 *     &lt;enumeration value="Place"/>
 *     &lt;enumeration value="Privacy"/>
 *     &lt;enumeration value="Sphere"/>
 *     &lt;enumeration value="Communication"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PresenceAttributeType")
@XmlEnum
public enum PresenceAttributeType {

    @XmlEnumValue("Activity")
    ACTIVITY("Activity"),
    @XmlEnumValue("Place")
    PLACE("Place"),
    @XmlEnumValue("Privacy")
    PRIVACY("Privacy"),
    @XmlEnumValue("Sphere")
    SPHERE("Sphere"),
    @XmlEnumValue("Communication")
    COMMUNICATION("Communication"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PresenceAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PresenceAttributeType fromValue(String v) {
        for (PresenceAttributeType c: PresenceAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
