//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence.v2_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrivacyValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrivacyValue">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PrivacyNone"/>
 *     &lt;enumeration value="PrivacyPublic"/>
 *     &lt;enumeration value="PrivacyPrivate"/>
 *     &lt;enumeration value="PrivacyQuiet"/>
 *     &lt;enumeration value="PrivacyOther"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrivacyValue")
@XmlEnum
public enum PrivacyValue {

    @XmlEnumValue("PrivacyNone")
    PRIVACY_NONE("PrivacyNone"),
    @XmlEnumValue("PrivacyPublic")
    PRIVACY_PUBLIC("PrivacyPublic"),
    @XmlEnumValue("PrivacyPrivate")
    PRIVACY_PRIVATE("PrivacyPrivate"),
    @XmlEnumValue("PrivacyQuiet")
    PRIVACY_QUIET("PrivacyQuiet"),
    @XmlEnumValue("PrivacyOther")
    PRIVACY_OTHER("PrivacyOther");
    private final String value;

    PrivacyValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrivacyValue fromValue(String v) {
        for (PrivacyValue c: PrivacyValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
