//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package com.nortel.xmlprotocol.wsdl.management.user_mgmt.v1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessControlRuleT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessControlRuleT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceName" type="{http://www.nortel.com/xmlprotocol/wsdl/management/user_mgmt/v1_5/}nonEmptyString"/>
 *         &lt;element name="serviceAccessMode" type="{http://www.nortel.com/xmlprotocol/wsdl/management/user_mgmt/v1_5/}ValidServiceAccessModeT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessControlRuleT", propOrder = {
    "serviceName",
    "serviceAccessMode"
})
public class AccessControlRuleT {

    @XmlElement(required = true)
    protected String serviceName;
    @XmlElement(required = true)
    protected ValidServiceAccessModeT serviceAccessMode;

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the serviceAccessMode property.
     * 
     * @return
     *     possible object is
     *     {@link ValidServiceAccessModeT }
     *     
     */
    public ValidServiceAccessModeT getServiceAccessMode() {
        return serviceAccessMode;
    }

    /**
     * Sets the value of the serviceAccessMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidServiceAccessModeT }
     *     
     */
    public void setServiceAccessMode(ValidServiceAccessModeT value) {
        this.serviceAccessMode = value;
    }

}
