//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package com.nortel.xmlprotocol.wsdl.management.user_mgmt.v1_5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nortel.xmlprotocol.wsdl.management.user_mgmt.v1_5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContactInfoTPin_QNAME = new QName("", "pin");
    private final static QName _UpdateContactInfoTPriority_QNAME = new QName("", "priority");
    private final static QName _UpdateContactInfoTContactName_QNAME = new QName("", "contactName");
    private final static QName _QueryUserNamesByContactIDRequestType_QNAME = new QName("", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nortel.xmlprotocol.wsdl.management.user_mgmt.v1_5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BulkAddBuddyGroupToUserProfileResponsesT }
     * 
     */
    public BulkAddBuddyGroupToUserProfileResponsesT createBulkAddBuddyGroupToUserProfileResponsesT() {
        return new BulkAddBuddyGroupToUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link BulkQueryUserGroupProfileResponseT }
     * 
     */
    public BulkQueryUserGroupProfileResponseT createBulkQueryUserGroupProfileResponseT() {
        return new BulkQueryUserGroupProfileResponseT();
    }

    /**
     * Create an instance of {@link PasswordRulesT }
     * 
     */
    public PasswordRulesT createPasswordRulesT() {
        return new PasswordRulesT();
    }

    /**
     * Create an instance of {@link RemoveContactInfoFromUserProfileResponse }
     * 
     */
    public RemoveContactInfoFromUserProfileResponse createRemoveContactInfoFromUserProfileResponse() {
        return new RemoveContactInfoFromUserProfileResponse();
    }

    /**
     * Create an instance of {@link RemoveUserProfileResponse }
     * 
     */
    public RemoveUserProfileResponse createRemoveUserProfileResponse() {
        return new RemoveUserProfileResponse();
    }

    /**
     * Create an instance of {@link QueryAllUserGroupNamesRequest }
     * 
     */
    public QueryAllUserGroupNamesRequest createQueryAllUserGroupNamesRequest() {
        return new QueryAllUserGroupNamesRequest();
    }

    /**
     * Create an instance of {@link AddBuddyGroupToUserProfileRequest }
     * 
     */
    public AddBuddyGroupToUserProfileRequest createAddBuddyGroupToUserProfileRequest() {
        return new AddBuddyGroupToUserProfileRequest();
    }

    /**
     * Create an instance of {@link BulkCreateUserGroupProfileResponseT }
     * 
     */
    public BulkCreateUserGroupProfileResponseT createBulkCreateUserGroupProfileResponseT() {
        return new BulkCreateUserGroupProfileResponseT();
    }

    /**
     * Create an instance of {@link QueryUserProfileResponse }
     * 
     */
    public QueryUserProfileResponse createQueryUserProfileResponse() {
        return new QueryUserProfileResponse();
    }

    /**
     * Create an instance of {@link AddContactInfoToUserProfileResponse }
     * 
     */
    public AddContactInfoToUserProfileResponse createAddContactInfoToUserProfileResponse() {
        return new AddContactInfoToUserProfileResponse();
    }

    /**
     * Create an instance of {@link ChangePasswordResponse }
     * 
     */
    public ChangePasswordResponse createChangePasswordResponse() {
        return new ChangePasswordResponse();
    }

    /**
     * Create an instance of {@link ContactIdentifiersT }
     * 
     */
    public ContactIdentifiersT createContactIdentifiersT() {
        return new ContactIdentifiersT();
    }

    /**
     * Create an instance of {@link BulkAddContactInfoToUserProfileResponsesT }
     * 
     */
    public BulkAddContactInfoToUserProfileResponsesT createBulkAddContactInfoToUserProfileResponsesT() {
        return new BulkAddContactInfoToUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link UpdateContactInfoT }
     * 
     */
    public UpdateContactInfoT createUpdateContactInfoT() {
        return new UpdateContactInfoT();
    }

    /**
     * Create an instance of {@link RemoveUserFromUserGroupRequest }
     * 
     */
    public RemoveUserFromUserGroupRequest createRemoveUserFromUserGroupRequest() {
        return new RemoveUserFromUserGroupRequest();
    }

    /**
     * Create an instance of {@link ChangePasswordRequest }
     * 
     */
    public ChangePasswordRequest createChangePasswordRequest() {
        return new ChangePasswordRequest();
    }

    /**
     * Create an instance of {@link QueryUserNamesByUserGroupRequest }
     * 
     */
    public QueryUserNamesByUserGroupRequest createQueryUserNamesByUserGroupRequest() {
        return new QueryUserNamesByUserGroupRequest();
    }

    /**
     * Create an instance of {@link BuddyGroupsT }
     * 
     */
    public BuddyGroupsT createBuddyGroupsT() {
        return new BuddyGroupsT();
    }

    /**
     * Create an instance of {@link BulkRemoveUserGroupProfileResponseT }
     * 
     */
    public BulkRemoveUserGroupProfileResponseT createBulkRemoveUserGroupProfileResponseT() {
        return new BulkRemoveUserGroupProfileResponseT();
    }

    /**
     * Create an instance of {@link RemoveBuddyGroupFromUserProfileResponse }
     * 
     */
    public RemoveBuddyGroupFromUserProfileResponse createRemoveBuddyGroupFromUserProfileResponse() {
        return new RemoveBuddyGroupFromUserProfileResponse();
    }

    /**
     * Create an instance of {@link RemoveUserFromUserGroupResponse }
     * 
     */
    public RemoveUserFromUserGroupResponse createRemoveUserFromUserGroupResponse() {
        return new RemoveUserFromUserGroupResponse();
    }

    /**
     * Create an instance of {@link UpdateGlobalSecuritySettingsRequest }
     * 
     */
    public UpdateGlobalSecuritySettingsRequest createUpdateGlobalSecuritySettingsRequest() {
        return new UpdateGlobalSecuritySettingsRequest();
    }

    /**
     * Create an instance of {@link RemoveContactInfoFromUserProfileRequest }
     * 
     */
    public RemoveContactInfoFromUserProfileRequest createRemoveContactInfoFromUserProfileRequest() {
        return new RemoveContactInfoFromUserProfileRequest();
    }

    /**
     * Create an instance of {@link BulkCreateUserProfileResponsesT }
     * 
     */
    public BulkCreateUserProfileResponsesT createBulkCreateUserProfileResponsesT() {
        return new BulkCreateUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link BuddyGroupNamesT }
     * 
     */
    public BuddyGroupNamesT createBuddyGroupNamesT() {
        return new BuddyGroupNamesT();
    }

    /**
     * Create an instance of {@link ContactsT }
     * 
     */
    public ContactsT createContactsT() {
        return new ContactsT();
    }

    /**
     * Create an instance of {@link BulkRemoveBuddyFromBuddyGroupResponsesT }
     * 
     */
    public BulkRemoveBuddyFromBuddyGroupResponsesT createBulkRemoveBuddyFromBuddyGroupResponsesT() {
        return new BulkRemoveBuddyFromBuddyGroupResponsesT();
    }

    /**
     * Create an instance of {@link RemoveUserGroupProfileRequest }
     * 
     */
    public RemoveUserGroupProfileRequest createRemoveUserGroupProfileRequest() {
        return new RemoveUserGroupProfileRequest();
    }

    /**
     * Create an instance of {@link QueryContactsT }
     * 
     */
    public QueryContactsT createQueryContactsT() {
        return new QueryContactsT();
    }

    /**
     * Create an instance of {@link BulkRemoveUserProfileResponseT }
     * 
     */
    public BulkRemoveUserProfileResponseT createBulkRemoveUserProfileResponseT() {
        return new BulkRemoveUserProfileResponseT();
    }

    /**
     * Create an instance of {@link BuddiesT }
     * 
     */
    public BuddiesT createBuddiesT() {
        return new BuddiesT();
    }

    /**
     * Create an instance of {@link BulkRemoveUserProfileResponsesT }
     * 
     */
    public BulkRemoveUserProfileResponsesT createBulkRemoveUserProfileResponsesT() {
        return new BulkRemoveUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link BulkCreateUserGroupProfileResponsesT }
     * 
     */
    public BulkCreateUserGroupProfileResponsesT createBulkCreateUserGroupProfileResponsesT() {
        return new BulkCreateUserGroupProfileResponsesT();
    }

    /**
     * Create an instance of {@link QueryGlobalSecuritySettingsResponse }
     * 
     */
    public QueryGlobalSecuritySettingsResponse createQueryGlobalSecuritySettingsResponse() {
        return new QueryGlobalSecuritySettingsResponse();
    }

    /**
     * Create an instance of {@link AddContactInfoToUserProfileRequest }
     * 
     */
    public AddContactInfoToUserProfileRequest createAddContactInfoToUserProfileRequest() {
        return new AddContactInfoToUserProfileRequest();
    }

    /**
     * Create an instance of {@link BulkQueryUserGroupProfileResponsesT }
     * 
     */
    public BulkQueryUserGroupProfileResponsesT createBulkQueryUserGroupProfileResponsesT() {
        return new BulkQueryUserGroupProfileResponsesT();
    }

    /**
     * Create an instance of {@link AccessControlRulesWithOperationsT }
     * 
     */
    public AccessControlRulesWithOperationsT createAccessControlRulesWithOperationsT() {
        return new AccessControlRulesWithOperationsT();
    }

    /**
     * Create an instance of {@link BulkQueryUserProfileResponseT }
     * 
     */
    public BulkQueryUserProfileResponseT createBulkQueryUserProfileResponseT() {
        return new BulkQueryUserProfileResponseT();
    }

    /**
     * Create an instance of {@link RemoveUserProfileRequest }
     * 
     */
    public RemoveUserProfileRequest createRemoveUserProfileRequest() {
        return new RemoveUserProfileRequest();
    }

    /**
     * Create an instance of {@link AddUserToUserGroupResponse }
     * 
     */
    public AddUserToUserGroupResponse createAddUserToUserGroupResponse() {
        return new AddUserToUserGroupResponse();
    }

    /**
     * Create an instance of {@link AddBuddyToBuddyGroupResponse }
     * 
     */
    public AddBuddyToBuddyGroupResponse createAddBuddyToBuddyGroupResponse() {
        return new AddBuddyToBuddyGroupResponse();
    }

    /**
     * Create an instance of {@link BulkCreateUserProfileResponseT }
     * 
     */
    public BulkCreateUserProfileResponseT createBulkCreateUserProfileResponseT() {
        return new BulkCreateUserProfileResponseT();
    }

    /**
     * Create an instance of {@link QueryUserGroupProfileResponse }
     * 
     */
    public QueryUserGroupProfileResponse createQueryUserGroupProfileResponse() {
        return new QueryUserGroupProfileResponse();
    }

    /**
     * Create an instance of {@link ContactInfoT }
     * 
     */
    public ContactInfoT createContactInfoT() {
        return new ContactInfoT();
    }

    /**
     * Create an instance of {@link BulkRemoveContactInfoFromUserProfileResponsesT }
     * 
     */
    public BulkRemoveContactInfoFromUserProfileResponsesT createBulkRemoveContactInfoFromUserProfileResponsesT() {
        return new BulkRemoveContactInfoFromUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link CreateUserGroupProfileRequest }
     * 
     */
    public CreateUserGroupProfileRequest createCreateUserGroupProfileRequest() {
        return new CreateUserGroupProfileRequest();
    }

    /**
     * Create an instance of {@link CreateUserProfileResponse }
     * 
     */
    public CreateUserProfileResponse createCreateUserProfileResponse() {
        return new CreateUserProfileResponse();
    }

    /**
     * Create an instance of {@link BulkRemoveContactInfoFromUserProfileResponseT }
     * 
     */
    public BulkRemoveContactInfoFromUserProfileResponseT createBulkRemoveContactInfoFromUserProfileResponseT() {
        return new BulkRemoveContactInfoFromUserProfileResponseT();
    }

    /**
     * Create an instance of {@link AccessControlRuleWithOperationT }
     * 
     */
    public AccessControlRuleWithOperationT createAccessControlRuleWithOperationT() {
        return new AccessControlRuleWithOperationT();
    }

    /**
     * Create an instance of {@link BulkUpdateContactInfoResponseT }
     * 
     */
    public BulkUpdateContactInfoResponseT createBulkUpdateContactInfoResponseT() {
        return new BulkUpdateContactInfoResponseT();
    }

    /**
     * Create an instance of {@link QueryUserProfileRequest }
     * 
     */
    public QueryUserProfileRequest createQueryUserProfileRequest() {
        return new QueryUserProfileRequest();
    }

    /**
     * Create an instance of {@link AddUserToUserGroupRequest }
     * 
     */
    public AddUserToUserGroupRequest createAddUserToUserGroupRequest() {
        return new AddUserToUserGroupRequest();
    }

    /**
     * Create an instance of {@link UpdatePersonalDataRequest }
     * 
     */
    public UpdatePersonalDataRequest createUpdatePersonalDataRequest() {
        return new UpdatePersonalDataRequest();
    }

    /**
     * Create an instance of {@link BuddGroupNamesT }
     * 
     */
    public BuddGroupNamesT createBuddGroupNamesT() {
        return new BuddGroupNamesT();
    }

    /**
     * Create an instance of {@link RemoveBuddyFromBuddyGroupRequest }
     * 
     */
    public RemoveBuddyFromBuddyGroupRequest createRemoveBuddyFromBuddyGroupRequest() {
        return new RemoveBuddyFromBuddyGroupRequest();
    }

    /**
     * Create an instance of {@link QueryContactInfoT }
     * 
     */
    public QueryContactInfoT createQueryContactInfoT() {
        return new QueryContactInfoT();
    }

    /**
     * Create an instance of {@link BulkAddBuddyToBuddyGroupResponsesT }
     * 
     */
    public BulkAddBuddyToBuddyGroupResponsesT createBulkAddBuddyToBuddyGroupResponsesT() {
        return new BulkAddBuddyToBuddyGroupResponsesT();
    }

    /**
     * Create an instance of {@link UpdateUserGroupPolicyResponse }
     * 
     */
    public UpdateUserGroupPolicyResponse createUpdateUserGroupPolicyResponse() {
        return new UpdateUserGroupPolicyResponse();
    }

    /**
     * Create an instance of {@link QueryUserNamesByContactIDResponse }
     * 
     */
    public QueryUserNamesByContactIDResponse createQueryUserNamesByContactIDResponse() {
        return new QueryUserNamesByContactIDResponse();
    }

    /**
     * Create an instance of {@link UpdateContactInfoRequest }
     * 
     */
    public UpdateContactInfoRequest createUpdateContactInfoRequest() {
        return new UpdateContactInfoRequest();
    }

    /**
     * Create an instance of {@link QueryUserGroupProfileRequest }
     * 
     */
    public QueryUserGroupProfileRequest createQueryUserGroupProfileRequest() {
        return new QueryUserGroupProfileRequest();
    }

    /**
     * Create an instance of {@link RemoveBuddyFromBuddyGroupResponse }
     * 
     */
    public RemoveBuddyFromBuddyGroupResponse createRemoveBuddyFromBuddyGroupResponse() {
        return new RemoveBuddyFromBuddyGroupResponse();
    }

    /**
     * Create an instance of {@link QueryAllUserGroupNamesResponse }
     * 
     */
    public QueryAllUserGroupNamesResponse createQueryAllUserGroupNamesResponse() {
        return new QueryAllUserGroupNamesResponse();
    }

    /**
     * Create an instance of {@link UnboundedUserGroupNamesT }
     * 
     */
    public UnboundedUserGroupNamesT createUnboundedUserGroupNamesT() {
        return new UnboundedUserGroupNamesT();
    }

    /**
     * Create an instance of {@link BulkAddBuddyToBuddyGroupResponseT }
     * 
     */
    public BulkAddBuddyToBuddyGroupResponseT createBulkAddBuddyToBuddyGroupResponseT() {
        return new BulkAddBuddyToBuddyGroupResponseT();
    }

    /**
     * Create an instance of {@link BuddyT }
     * 
     */
    public BuddyT createBuddyT() {
        return new BuddyT();
    }

    /**
     * Create an instance of {@link UserNamesT }
     * 
     */
    public UserNamesT createUserNamesT() {
        return new UserNamesT();
    }

    /**
     * Create an instance of {@link BuddyGroupT }
     * 
     */
    public BuddyGroupT createBuddyGroupT() {
        return new BuddyGroupT();
    }

    /**
     * Create an instance of {@link BulkRemoveBuddyGroupFromUserProfileResponsesT }
     * 
     */
    public BulkRemoveBuddyGroupFromUserProfileResponsesT createBulkRemoveBuddyGroupFromUserProfileResponsesT() {
        return new BulkRemoveBuddyGroupFromUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link AccessControlRulesT }
     * 
     */
    public AccessControlRulesT createAccessControlRulesT() {
        return new AccessControlRulesT();
    }

    /**
     * Create an instance of {@link UpdateContactInfoResponse }
     * 
     */
    public UpdateContactInfoResponse createUpdateContactInfoResponse() {
        return new UpdateContactInfoResponse();
    }

    /**
     * Create an instance of {@link UpdatePersonalDataResponse }
     * 
     */
    public UpdatePersonalDataResponse createUpdatePersonalDataResponse() {
        return new UpdatePersonalDataResponse();
    }

    /**
     * Create an instance of {@link QueryUserGroupPolicyRequest }
     * 
     */
    public QueryUserGroupPolicyRequest createQueryUserGroupPolicyRequest() {
        return new QueryUserGroupPolicyRequest();
    }

    /**
     * Create an instance of {@link UserGroupT }
     * 
     */
    public UserGroupT createUserGroupT() {
        return new UserGroupT();
    }

    /**
     * Create an instance of {@link BulkRemoveBuddyGroupFromUserProfileResponseT }
     * 
     */
    public BulkRemoveBuddyGroupFromUserProfileResponseT createBulkRemoveBuddyGroupFromUserProfileResponseT() {
        return new BulkRemoveBuddyGroupFromUserProfileResponseT();
    }

    /**
     * Create an instance of {@link QueryUserNamesByContactIDRequest }
     * 
     */
    public QueryUserNamesByContactIDRequest createQueryUserNamesByContactIDRequest() {
        return new QueryUserNamesByContactIDRequest();
    }

    /**
     * Create an instance of {@link RemoveUserGroupProfileResponse }
     * 
     */
    public RemoveUserGroupProfileResponse createRemoveUserGroupProfileResponse() {
        return new RemoveUserGroupProfileResponse();
    }

    /**
     * Create an instance of {@link BulkRemoveUserGroupProfileResponsesT }
     * 
     */
    public BulkRemoveUserGroupProfileResponsesT createBulkRemoveUserGroupProfileResponsesT() {
        return new BulkRemoveUserGroupProfileResponsesT();
    }

    /**
     * Create an instance of {@link PasswordPolicyT }
     * 
     */
    public PasswordPolicyT createPasswordPolicyT() {
        return new PasswordPolicyT();
    }

    /**
     * Create an instance of {@link UpdateGlobalSecuritySettingsResponse }
     * 
     */
    public UpdateGlobalSecuritySettingsResponse createUpdateGlobalSecuritySettingsResponse() {
        return new UpdateGlobalSecuritySettingsResponse();
    }

    /**
     * Create an instance of {@link RemoveBuddyGroupFromUserProfileRequest }
     * 
     */
    public RemoveBuddyGroupFromUserProfileRequest createRemoveBuddyGroupFromUserProfileRequest() {
        return new RemoveBuddyGroupFromUserProfileRequest();
    }

    /**
     * Create an instance of {@link ServiceOperationT }
     * 
     */
    public ServiceOperationT createServiceOperationT() {
        return new ServiceOperationT();
    }

    /**
     * Create an instance of {@link BasicUsersT }
     * 
     */
    public BasicUsersT createBasicUsersT() {
        return new BasicUsersT();
    }

    /**
     * Create an instance of {@link BulkAddBuddyGroupToUserProfileResponseT }
     * 
     */
    public BulkAddBuddyGroupToUserProfileResponseT createBulkAddBuddyGroupToUserProfileResponseT() {
        return new BulkAddBuddyGroupToUserProfileResponseT();
    }

    /**
     * Create an instance of {@link CreateUserGroupProfileResponse }
     * 
     */
    public CreateUserGroupProfileResponse createCreateUserGroupProfileResponse() {
        return new CreateUserGroupProfileResponse();
    }

    /**
     * Create an instance of {@link AddBuddyToBuddyGroupRequest }
     * 
     */
    public AddBuddyToBuddyGroupRequest createAddBuddyToBuddyGroupRequest() {
        return new AddBuddyToBuddyGroupRequest();
    }

    /**
     * Create an instance of {@link QueryUserNamesByUserGroupResponse }
     * 
     */
    public QueryUserNamesByUserGroupResponse createQueryUserNamesByUserGroupResponse() {
        return new QueryUserNamesByUserGroupResponse();
    }

    /**
     * Create an instance of {@link BulkUpdateContactInfoResponsesT }
     * 
     */
    public BulkUpdateContactInfoResponsesT createBulkUpdateContactInfoResponsesT() {
        return new BulkUpdateContactInfoResponsesT();
    }

    /**
     * Create an instance of {@link BasicUserT }
     * 
     */
    public BasicUserT createBasicUserT() {
        return new BasicUserT();
    }

    /**
     * Create an instance of {@link UserT }
     * 
     */
    public UserT createUserT() {
        return new UserT();
    }

    /**
     * Create an instance of {@link BasicUserGroupsT }
     * 
     */
    public BasicUserGroupsT createBasicUserGroupsT() {
        return new BasicUserGroupsT();
    }

    /**
     * Create an instance of {@link UnboundedUserNamesT }
     * 
     */
    public UnboundedUserNamesT createUnboundedUserNamesT() {
        return new UnboundedUserNamesT();
    }

    /**
     * Create an instance of {@link QueryUserGroupPolicyResponse }
     * 
     */
    public QueryUserGroupPolicyResponse createQueryUserGroupPolicyResponse() {
        return new QueryUserGroupPolicyResponse();
    }

    /**
     * Create an instance of {@link BulkQueryUserProfileResponsesT }
     * 
     */
    public BulkQueryUserProfileResponsesT createBulkQueryUserProfileResponsesT() {
        return new BulkQueryUserProfileResponsesT();
    }

    /**
     * Create an instance of {@link UserGroupNamesT }
     * 
     */
    public UserGroupNamesT createUserGroupNamesT() {
        return new UserGroupNamesT();
    }

    /**
     * Create an instance of {@link BulkAddContactInfoToUserProfileResponseT }
     * 
     */
    public BulkAddContactInfoToUserProfileResponseT createBulkAddContactInfoToUserProfileResponseT() {
        return new BulkAddContactInfoToUserProfileResponseT();
    }

    /**
     * Create an instance of {@link UpdateUserGroupPolicyRequest }
     * 
     */
    public UpdateUserGroupPolicyRequest createUpdateUserGroupPolicyRequest() {
        return new UpdateUserGroupPolicyRequest();
    }

    /**
     * Create an instance of {@link BulkRemoveBuddyFromBuddyGroupResponseT }
     * 
     */
    public BulkRemoveBuddyFromBuddyGroupResponseT createBulkRemoveBuddyFromBuddyGroupResponseT() {
        return new BulkRemoveBuddyFromBuddyGroupResponseT();
    }

    /**
     * Create an instance of {@link ServiceOperationsT }
     * 
     */
    public ServiceOperationsT createServiceOperationsT() {
        return new ServiceOperationsT();
    }

    /**
     * Create an instance of {@link PersonalDataT }
     * 
     */
    public PersonalDataT createPersonalDataT() {
        return new PersonalDataT();
    }

    /**
     * Create an instance of {@link BasicUserGroupT }
     * 
     */
    public BasicUserGroupT createBasicUserGroupT() {
        return new BasicUserGroupT();
    }

    /**
     * Create an instance of {@link CreateUserProfileRequest }
     * 
     */
    public CreateUserProfileRequest createCreateUserProfileRequest() {
        return new CreateUserProfileRequest();
    }

    /**
     * Create an instance of {@link AccessControlRuleT }
     * 
     */
    public AccessControlRuleT createAccessControlRuleT() {
        return new AccessControlRuleT();
    }

    /**
     * Create an instance of {@link BuddyNamesT }
     * 
     */
    public BuddyNamesT createBuddyNamesT() {
        return new BuddyNamesT();
    }

    /**
     * Create an instance of {@link QueryGlobalSecuritySettingsRequest }
     * 
     */
    public QueryGlobalSecuritySettingsRequest createQueryGlobalSecuritySettingsRequest() {
        return new QueryGlobalSecuritySettingsRequest();
    }

    /**
     * Create an instance of {@link AddBuddyGroupToUserProfileResponse }
     * 
     */
    public AddBuddyGroupToUserProfileResponse createAddBuddyGroupToUserProfileResponse() {
        return new AddBuddyGroupToUserProfileResponse();
    }

    /**
     * Create an instance of {@link UpdateContactsT }
     * 
     */
    public UpdateContactsT createUpdateContactsT() {
        return new UpdateContactsT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pin", scope = ContactInfoT.class)
    public JAXBElement<String> createContactInfoTPin(String value) {
        return new JAXBElement<String>(_ContactInfoTPin_QNAME, String.class, ContactInfoT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pin", scope = UpdateContactInfoT.class)
    public JAXBElement<String> createUpdateContactInfoTPin(String value) {
        return new JAXBElement<String>(_ContactInfoTPin_QNAME, String.class, UpdateContactInfoT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority", scope = UpdateContactInfoT.class)
    public JAXBElement<Float> createUpdateContactInfoTPriority(Float value) {
        return new JAXBElement<Float>(_UpdateContactInfoTPriority_QNAME, Float.class, UpdateContactInfoT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactName", scope = UpdateContactInfoT.class)
    public JAXBElement<String> createUpdateContactInfoTContactName(String value) {
        return new JAXBElement<String>(_UpdateContactInfoTContactName_QNAME, String.class, UpdateContactInfoT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidContactTypeT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = QueryUserNamesByContactIDRequest.class)
    public JAXBElement<ValidContactTypeT> createQueryUserNamesByContactIDRequestType(ValidContactTypeT value) {
        return new JAXBElement<ValidContactTypeT>(_QueryUserNamesByContactIDRequestType_QNAME, ValidContactTypeT.class, QueryUserNamesByContactIDRequest.class, value);
    }

}
