//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package com.nortel.xmlprotocol.wsdl.management.user_mgmt.v1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PasswordRulesT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PasswordRulesT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="minPasswordLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="minDifferentCharacters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="mixedCase" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="minAlphaCharacters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="minSpecialCharacters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="permittedSpecialCharacters" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="minNumericCharacters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PasswordRulesT", propOrder = {
    "minPasswordLength",
    "minDifferentCharacters",
    "mixedCase",
    "minAlphaCharacters",
    "minSpecialCharacters",
    "permittedSpecialCharacters",
    "minNumericCharacters"
})
public class PasswordRulesT {

    protected Integer minPasswordLength;
    protected Integer minDifferentCharacters;
    protected Boolean mixedCase;
    protected Integer minAlphaCharacters;
    protected Integer minSpecialCharacters;
    protected String permittedSpecialCharacters;
    protected Integer minNumericCharacters;

    /**
     * Gets the value of the minPasswordLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinPasswordLength() {
        return minPasswordLength;
    }

    /**
     * Sets the value of the minPasswordLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinPasswordLength(Integer value) {
        this.minPasswordLength = value;
    }

    /**
     * Gets the value of the minDifferentCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinDifferentCharacters() {
        return minDifferentCharacters;
    }

    /**
     * Sets the value of the minDifferentCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinDifferentCharacters(Integer value) {
        this.minDifferentCharacters = value;
    }

    /**
     * Gets the value of the mixedCase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMixedCase() {
        return mixedCase;
    }

    /**
     * Sets the value of the mixedCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMixedCase(Boolean value) {
        this.mixedCase = value;
    }

    /**
     * Gets the value of the minAlphaCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinAlphaCharacters() {
        return minAlphaCharacters;
    }

    /**
     * Sets the value of the minAlphaCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinAlphaCharacters(Integer value) {
        this.minAlphaCharacters = value;
    }

    /**
     * Gets the value of the minSpecialCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinSpecialCharacters() {
        return minSpecialCharacters;
    }

    /**
     * Sets the value of the minSpecialCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinSpecialCharacters(Integer value) {
        this.minSpecialCharacters = value;
    }

    /**
     * Gets the value of the permittedSpecialCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermittedSpecialCharacters() {
        return permittedSpecialCharacters;
    }

    /**
     * Sets the value of the permittedSpecialCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermittedSpecialCharacters(String value) {
        this.permittedSpecialCharacters = value;
    }

    /**
     * Gets the value of the minNumericCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinNumericCharacters() {
        return minNumericCharacters;
    }

    /**
     * Sets the value of the minNumericCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinNumericCharacters(Integer value) {
        this.minNumericCharacters = value;
    }

}
