//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence.v3_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlaceTypeValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlaceTypeValue">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PlaceNone"/>
 *     &lt;enumeration value="Arena"/>
 *     &lt;enumeration value="Home"/>
 *     &lt;enumeration value="Office"/>
 *     &lt;enumeration value="PublicTransport"/>
 *     &lt;enumeration value="Street"/>
 *     &lt;enumeration value="Outdoors"/>
 *     &lt;enumeration value="PublicPlace"/>
 *     &lt;enumeration value="Hotel"/>
 *     &lt;enumeration value="Theatre"/>
 *     &lt;enumeration value="Restaurant"/>
 *     &lt;enumeration value="School"/>
 *     &lt;enumeration value="Industrial"/>
 *     &lt;enumeration value="Quiet"/>
 *     &lt;enumeration value="Noisy"/>
 *     &lt;enumeration value="Aircraft"/>
 *     &lt;enumeration value="Watercraft"/>
 *     &lt;enumeration value="Automobile"/>
 *     &lt;enumeration value="Bus"/>
 *     &lt;enumeration value="BusStation"/>
 *     &lt;enumeration value="TrainStation"/>
 *     &lt;enumeration value="ShoppingArea"/>
 *     &lt;enumeration value="Airport"/>
 *     &lt;enumeration value="Train"/>
 *     &lt;enumeration value="Bank"/>
 *     &lt;enumeration value="Bar"/>
 *     &lt;enumeration value="Bicycle"/>
 *     &lt;enumeration value="Cafe"/>
 *     &lt;enumeration value="Classroom"/>
 *     &lt;enumeration value="Club"/>
 *     &lt;enumeration value="Construction"/>
 *     &lt;enumeration value="ConventionCenter"/>
 *     &lt;enumeration value="Government"/>
 *     &lt;enumeration value="Hospital"/>
 *     &lt;enumeration value="Library"/>
 *     &lt;enumeration value="Motorcycle"/>
 *     &lt;enumeration value="Parking"/>
 *     &lt;enumeration value="PlaceOfWorship"/>
 *     &lt;enumeration value="Prison"/>
 *     &lt;enumeration value="Residence"/>
 *     &lt;enumeration value="Stadium"/>
 *     &lt;enumeration value="Store"/>
 *     &lt;enumeration value="Truck"/>
 *     &lt;enumeration value="Underway"/>
 *     &lt;enumeration value="Warehouse"/>
 *     &lt;enumeration value="Water"/>
 *     &lt;enumeration value="PlaceOther"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlaceTypeValue")
@XmlEnum
public enum PlaceTypeValue {

    @XmlEnumValue("PlaceNone")
    PLACE_NONE("PlaceNone"),
    @XmlEnumValue("Arena")
    ARENA("Arena"),
    @XmlEnumValue("Home")
    HOME("Home"),
    @XmlEnumValue("Office")
    OFFICE("Office"),
    @XmlEnumValue("PublicTransport")
    PUBLIC_TRANSPORT("PublicTransport"),
    @XmlEnumValue("Street")
    STREET("Street"),
    @XmlEnumValue("Outdoors")
    OUTDOORS("Outdoors"),
    @XmlEnumValue("PublicPlace")
    PUBLIC_PLACE("PublicPlace"),
    @XmlEnumValue("Hotel")
    HOTEL("Hotel"),
    @XmlEnumValue("Theatre")
    THEATRE("Theatre"),
    @XmlEnumValue("Restaurant")
    RESTAURANT("Restaurant"),
    @XmlEnumValue("School")
    SCHOOL("School"),
    @XmlEnumValue("Industrial")
    INDUSTRIAL("Industrial"),
    @XmlEnumValue("Quiet")
    QUIET("Quiet"),
    @XmlEnumValue("Noisy")
    NOISY("Noisy"),
    @XmlEnumValue("Aircraft")
    AIRCRAFT("Aircraft"),
    @XmlEnumValue("Watercraft")
    WATERCRAFT("Watercraft"),
    @XmlEnumValue("Automobile")
    AUTOMOBILE("Automobile"),
    @XmlEnumValue("Bus")
    BUS("Bus"),
    @XmlEnumValue("BusStation")
    BUS_STATION("BusStation"),
    @XmlEnumValue("TrainStation")
    TRAIN_STATION("TrainStation"),
    @XmlEnumValue("ShoppingArea")
    SHOPPING_AREA("ShoppingArea"),
    @XmlEnumValue("Airport")
    AIRPORT("Airport"),
    @XmlEnumValue("Train")
    TRAIN("Train"),
    @XmlEnumValue("Bank")
    BANK("Bank"),
    @XmlEnumValue("Bar")
    BAR("Bar"),
    @XmlEnumValue("Bicycle")
    BICYCLE("Bicycle"),
    @XmlEnumValue("Cafe")
    CAFE("Cafe"),
    @XmlEnumValue("Classroom")
    CLASSROOM("Classroom"),
    @XmlEnumValue("Club")
    CLUB("Club"),
    @XmlEnumValue("Construction")
    CONSTRUCTION("Construction"),
    @XmlEnumValue("ConventionCenter")
    CONVENTION_CENTER("ConventionCenter"),
    @XmlEnumValue("Government")
    GOVERNMENT("Government"),
    @XmlEnumValue("Hospital")
    HOSPITAL("Hospital"),
    @XmlEnumValue("Library")
    LIBRARY("Library"),
    @XmlEnumValue("Motorcycle")
    MOTORCYCLE("Motorcycle"),
    @XmlEnumValue("Parking")
    PARKING("Parking"),
    @XmlEnumValue("PlaceOfWorship")
    PLACE_OF_WORSHIP("PlaceOfWorship"),
    @XmlEnumValue("Prison")
    PRISON("Prison"),
    @XmlEnumValue("Residence")
    RESIDENCE("Residence"),
    @XmlEnumValue("Stadium")
    STADIUM("Stadium"),
    @XmlEnumValue("Store")
    STORE("Store"),
    @XmlEnumValue("Truck")
    TRUCK("Truck"),
    @XmlEnumValue("Underway")
    UNDERWAY("Underway"),
    @XmlEnumValue("Warehouse")
    WAREHOUSE("Warehouse"),
    @XmlEnumValue("Water")
    WATER("Water"),
    @XmlEnumValue("PlaceOther")
    PLACE_OTHER("PlaceOther");
    private final String value;

    PlaceTypeValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlaceTypeValue fromValue(String v) {
        for (PlaceTypeValue c: PlaceTypeValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
