//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.presence.consumer.v3_2.local;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.csapi.schema.parlayx.common.v3_1.SimpleReference;
import org.csapi.schema.parlayx.common.v3_1.TimeMetric;
import org.csapi.schema.parlayx.presence.v3_2.PresenceAttributeType;


/**
 * <p>Java class for startPresenceNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="startPresenceNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="watcher" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="presentities" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *         &lt;element name="attributes" type="{http://www.csapi.org/schema/parlayx/presence/v3_2}PresenceAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://www.csapi.org/schema/parlayx/common/v3_1}SimpleReference"/>
 *         &lt;element name="frequency" type="{http://www.csapi.org/schema/parlayx/common/v3_1}TimeMetric"/>
 *         &lt;element name="duration" type="{http://www.csapi.org/schema/parlayx/common/v3_1}TimeMetric" minOccurs="0"/>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="checkImmediate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="noFail" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "startPresenceNotification", propOrder = {
    "watcher",
    "presentities",
    "attributes",
    "reference",
    "frequency",
    "duration",
    "count",
    "checkImmediate",
    "noFail"
})
public class StartPresenceNotification {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String watcher;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected List<String> presentities;
    protected List<PresenceAttributeType> attributes;
    @XmlElement(required = true)
    protected SimpleReference reference;
    @XmlElement(required = true)
    protected TimeMetric frequency;
    protected TimeMetric duration;
    protected Integer count;
    protected boolean checkImmediate;
    protected Boolean noFail;

    /**
     * Gets the value of the watcher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWatcher() {
        return watcher;
    }

    /**
     * Sets the value of the watcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWatcher(String value) {
        this.watcher = value;
    }

    /**
     * Gets the value of the presentities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPresentities() {
        if (presentities == null) {
            presentities = new ArrayList<String>();
        }
        return this.presentities;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PresenceAttributeType }
     * 
     * 
     */
    public List<PresenceAttributeType> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<PresenceAttributeType>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleReference }
     *     
     */
    public SimpleReference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleReference }
     *     
     */
    public void setReference(SimpleReference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetric }
     *     
     */
    public TimeMetric getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetric }
     *     
     */
    public void setFrequency(TimeMetric value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetric }
     *     
     */
    public TimeMetric getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetric }
     *     
     */
    public void setDuration(TimeMetric value) {
        this.duration = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

    /**
     * Gets the value of the checkImmediate property.
     * 
     */
    public boolean isCheckImmediate() {
        return checkImmediate;
    }

    /**
     * Sets the value of the checkImmediate property.
     * 
     */
    public void setCheckImmediate(boolean value) {
        this.checkImmediate = value;
    }

    /**
     * Gets the value of the noFail property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoFail() {
        return noFail;
    }

    /**
     * Sets the value of the noFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoFail(Boolean value) {
        this.noFail = value;
    }

}
