//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package com.nortel.xmlprotocol.wsdl.utilities.system_monitoring.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemInfoT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemInfoT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationUpTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="applicationRestartToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemInfoT", propOrder = {
    "applicationUpTime",
    "applicationRestartToken"
})
public class SystemInfoT {

    protected long applicationUpTime;
    @XmlElement(required = true)
    protected String applicationRestartToken;

    /**
     * Gets the value of the applicationUpTime property.
     * 
     */
    public long getApplicationUpTime() {
        return applicationUpTime;
    }

    /**
     * Sets the value of the applicationUpTime property.
     * 
     */
    public void setApplicationUpTime(long value) {
        this.applicationUpTime = value;
    }

    /**
     * Gets the value of the applicationRestartToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationRestartToken() {
        return applicationRestartToken;
    }

    /**
     * Sets the value of the applicationRestartToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationRestartToken(String value) {
        this.applicationRestartToken = value;
    }

}
