//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.multimedia_conference.v3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ConferenceInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConferenceInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.csapi.org/schema/parlayx/multimedia_conference/v3_0}ConferenceStatus"/>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="numberOfParticipants" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maximumNumberOfParticipants" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="conferenceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="conferenceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConferenceInfo", propOrder = {
    "status",
    "startTime",
    "duration",
    "owner",
    "numberOfParticipants",
    "maximumNumberOfParticipants",
    "conferenceIdentifier",
    "conferenceDescription"
})
public class ConferenceInfo {

    @XmlElement(required = true)
    protected ConferenceStatus status;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    protected int duration;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String owner;
    protected int numberOfParticipants;
    protected int maximumNumberOfParticipants;
    @XmlElement(required = true)
    protected String conferenceIdentifier;
    @XmlElement(required = true)
    protected String conferenceDescription;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ConferenceStatus }
     *     
     */
    public ConferenceStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConferenceStatus }
     *     
     */
    public void setStatus(ConferenceStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public int getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(int value) {
        this.duration = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the numberOfParticipants property.
     * 
     */
    public int getNumberOfParticipants() {
        return numberOfParticipants;
    }

    /**
     * Sets the value of the numberOfParticipants property.
     * 
     */
    public void setNumberOfParticipants(int value) {
        this.numberOfParticipants = value;
    }

    /**
     * Gets the value of the maximumNumberOfParticipants property.
     * 
     */
    public int getMaximumNumberOfParticipants() {
        return maximumNumberOfParticipants;
    }

    /**
     * Sets the value of the maximumNumberOfParticipants property.
     * 
     */
    public void setMaximumNumberOfParticipants(int value) {
        this.maximumNumberOfParticipants = value;
    }

    /**
     * Gets the value of the conferenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConferenceIdentifier() {
        return conferenceIdentifier;
    }

    /**
     * Sets the value of the conferenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConferenceIdentifier(String value) {
        this.conferenceIdentifier = value;
    }

    /**
     * Gets the value of the conferenceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConferenceDescription() {
        return conferenceDescription;
    }

    /**
     * Sets the value of the conferenceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConferenceDescription(String value) {
        this.conferenceDescription = value;
    }

}
