//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.third_party_call.v2_3.local;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.csapi.schema.parlayx.common.v2_1.ChargingInformation;


/**
 * <p>Java class for makeCall complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="makeCall">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="callingParty" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="calledParty" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="charging" type="{http://www.csapi.org/schema/parlayx/common/v2_1}ChargingInformation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "makeCall", propOrder = {
    "callingParty",
    "calledParty",
    "charging"
})
public class MakeCall {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String callingParty;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String calledParty;
    protected ChargingInformation charging;

    /**
     * Gets the value of the callingParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallingParty() {
        return callingParty;
    }

    /**
     * Sets the value of the callingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallingParty(String value) {
        this.callingParty = value;
    }

    /**
     * Gets the value of the calledParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalledParty() {
        return calledParty;
    }

    /**
     * Sets the value of the calledParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalledParty(String value) {
        this.calledParty = value;
    }

    /**
     * Gets the value of the charging property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingInformation }
     *     
     */
    public ChargingInformation getCharging() {
        return charging;
    }

    /**
     * Sets the value of the charging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingInformation }
     *     
     */
    public void setCharging(ChargingInformation value) {
        this.charging = value;
    }

}
