//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.terminal_location.notification.v3_0.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.terminal_location.notification.v3_0.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LocationNotification_QNAME = new QName("http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", "locationNotification");
    private final static QName _LocationNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", "locationNotificationResponse");
    private final static QName _LocationEndResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", "locationEndResponse");
    private final static QName _LocationEnd_QNAME = new QName("http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", "locationEnd");
    private final static QName _LocationErrorResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", "locationErrorResponse");
    private final static QName _LocationError_QNAME = new QName("http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", "locationError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.terminal_location.notification.v3_0.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocationNotificationResponse }
     * 
     */
    public LocationNotificationResponse createLocationNotificationResponse() {
        return new LocationNotificationResponse();
    }

    /**
     * Create an instance of {@link LocationNotification }
     * 
     */
    public LocationNotification createLocationNotification() {
        return new LocationNotification();
    }

    /**
     * Create an instance of {@link LocationError }
     * 
     */
    public LocationError createLocationError() {
        return new LocationError();
    }

    /**
     * Create an instance of {@link LocationErrorResponse }
     * 
     */
    public LocationErrorResponse createLocationErrorResponse() {
        return new LocationErrorResponse();
    }

    /**
     * Create an instance of {@link LocationEndResponse }
     * 
     */
    public LocationEndResponse createLocationEndResponse() {
        return new LocationEndResponse();
    }

    /**
     * Create an instance of {@link LocationEnd }
     * 
     */
    public LocationEnd createLocationEnd() {
        return new LocationEnd();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", name = "locationNotification")
    public JAXBElement<LocationNotification> createLocationNotification(LocationNotification value) {
        return new JAXBElement<LocationNotification>(_LocationNotification_QNAME, LocationNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", name = "locationNotificationResponse")
    public JAXBElement<LocationNotificationResponse> createLocationNotificationResponse(LocationNotificationResponse value) {
        return new JAXBElement<LocationNotificationResponse>(_LocationNotificationResponse_QNAME, LocationNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationEndResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", name = "locationEndResponse")
    public JAXBElement<LocationEndResponse> createLocationEndResponse(LocationEndResponse value) {
        return new JAXBElement<LocationEndResponse>(_LocationEndResponse_QNAME, LocationEndResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationEnd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", name = "locationEnd")
    public JAXBElement<LocationEnd> createLocationEnd(LocationEnd value) {
        return new JAXBElement<LocationEnd>(_LocationEnd_QNAME, LocationEnd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationErrorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", name = "locationErrorResponse")
    public JAXBElement<LocationErrorResponse> createLocationErrorResponse(LocationErrorResponse value) {
        return new JAXBElement<LocationErrorResponse>(_LocationErrorResponse_QNAME, LocationErrorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationError }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/terminal_location/notification/v3_0/local", name = "locationError")
    public JAXBElement<LocationError> createLocationError(LocationError value) {
        return new JAXBElement<LocationError>(_LocationError_QNAME, LocationError.class, null, value);
    }

}
