//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ионГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nortel.com/xmlprotocol/wsdl/communications/services/ipc/v1_0/")
package com.nortel.xmlprotocol.wsdl.communications.services.ipc.v1_0;
