//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.call_direction.notification_manager.v3_1.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.call_direction.notification_manager.v3_1.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StopCallDirectionNotification_QNAME = new QName("http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", "stopCallDirectionNotification");
    private final static QName _StopCallDirectionNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", "stopCallDirectionNotificationResponse");
    private final static QName _StartCallDirectionNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", "startCallDirectionNotificationResponse");
    private final static QName _StartCallDirectionNotification_QNAME = new QName("http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", "startCallDirectionNotification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.call_direction.notification_manager.v3_1.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StopCallDirectionNotificationResponse }
     * 
     */
    public StopCallDirectionNotificationResponse createStopCallDirectionNotificationResponse() {
        return new StopCallDirectionNotificationResponse();
    }

    /**
     * Create an instance of {@link StopCallDirectionNotification }
     * 
     */
    public StopCallDirectionNotification createStopCallDirectionNotification() {
        return new StopCallDirectionNotification();
    }

    /**
     * Create an instance of {@link StartCallDirectionNotificationResponse }
     * 
     */
    public StartCallDirectionNotificationResponse createStartCallDirectionNotificationResponse() {
        return new StartCallDirectionNotificationResponse();
    }

    /**
     * Create an instance of {@link StartCallDirectionNotification }
     * 
     */
    public StartCallDirectionNotification createStartCallDirectionNotification() {
        return new StartCallDirectionNotification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StopCallDirectionNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", name = "stopCallDirectionNotification")
    public JAXBElement<StopCallDirectionNotification> createStopCallDirectionNotification(StopCallDirectionNotification value) {
        return new JAXBElement<StopCallDirectionNotification>(_StopCallDirectionNotification_QNAME, StopCallDirectionNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StopCallDirectionNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", name = "stopCallDirectionNotificationResponse")
    public JAXBElement<StopCallDirectionNotificationResponse> createStopCallDirectionNotificationResponse(StopCallDirectionNotificationResponse value) {
        return new JAXBElement<StopCallDirectionNotificationResponse>(_StopCallDirectionNotificationResponse_QNAME, StopCallDirectionNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartCallDirectionNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", name = "startCallDirectionNotificationResponse")
    public JAXBElement<StartCallDirectionNotificationResponse> createStartCallDirectionNotificationResponse(StartCallDirectionNotificationResponse value) {
        return new JAXBElement<StartCallDirectionNotificationResponse>(_StartCallDirectionNotificationResponse_QNAME, StartCallDirectionNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartCallDirectionNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/call_direction/notification_manager/v3_1/local", name = "startCallDirectionNotification")
    public JAXBElement<StartCallDirectionNotification> createStartCallDirectionNotification(StartCallDirectionNotification value) {
        return new JAXBElement<StartCallDirectionNotification>(_StartCallDirectionNotification_QNAME, StartCallDirectionNotification.class, null, value);
    }

}
