//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.26 at 11:20:45 ÉÏÎç CST 
//


package org.csapi.schema.parlayx.group_member.v2_1.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.group_member.v2_1.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddMemberAttributeResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/group_member/v2_1/local", "addMemberAttributeResponse");
    private final static QName _DeleteMemberAttributeResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/group_member/v2_1/local", "deleteMemberAttributeResponse");
    private final static QName _QueryMemberAttributesResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/group_member/v2_1/local", "queryMemberAttributesResponse");
    private final static QName _AddMemberAttribute_QNAME = new QName("http://www.csapi.org/schema/parlayx/group_member/v2_1/local", "addMemberAttribute");
    private final static QName _QueryMemberAttributes_QNAME = new QName("http://www.csapi.org/schema/parlayx/group_member/v2_1/local", "queryMemberAttributes");
    private final static QName _DeleteMemberAttribute_QNAME = new QName("http://www.csapi.org/schema/parlayx/group_member/v2_1/local", "deleteMemberAttribute");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.group_member.v2_1.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryMemberAttributesResponse }
     * 
     */
    public QueryMemberAttributesResponse createQueryMemberAttributesResponse() {
        return new QueryMemberAttributesResponse();
    }

    /**
     * Create an instance of {@link DeleteMemberAttribute }
     * 
     */
    public DeleteMemberAttribute createDeleteMemberAttribute() {
        return new DeleteMemberAttribute();
    }

    /**
     * Create an instance of {@link AddMemberAttributeResponse }
     * 
     */
    public AddMemberAttributeResponse createAddMemberAttributeResponse() {
        return new AddMemberAttributeResponse();
    }

    /**
     * Create an instance of {@link AddMemberAttribute }
     * 
     */
    public AddMemberAttribute createAddMemberAttribute() {
        return new AddMemberAttribute();
    }

    /**
     * Create an instance of {@link DeleteMemberAttributeResponse }
     * 
     */
    public DeleteMemberAttributeResponse createDeleteMemberAttributeResponse() {
        return new DeleteMemberAttributeResponse();
    }

    /**
     * Create an instance of {@link QueryMemberAttributes }
     * 
     */
    public QueryMemberAttributes createQueryMemberAttributes() {
        return new QueryMemberAttributes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddMemberAttributeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/group_member/v2_1/local", name = "addMemberAttributeResponse")
    public JAXBElement<AddMemberAttributeResponse> createAddMemberAttributeResponse(AddMemberAttributeResponse value) {
        return new JAXBElement<AddMemberAttributeResponse>(_AddMemberAttributeResponse_QNAME, AddMemberAttributeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMemberAttributeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/group_member/v2_1/local", name = "deleteMemberAttributeResponse")
    public JAXBElement<DeleteMemberAttributeResponse> createDeleteMemberAttributeResponse(DeleteMemberAttributeResponse value) {
        return new JAXBElement<DeleteMemberAttributeResponse>(_DeleteMemberAttributeResponse_QNAME, DeleteMemberAttributeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryMemberAttributesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/group_member/v2_1/local", name = "queryMemberAttributesResponse")
    public JAXBElement<QueryMemberAttributesResponse> createQueryMemberAttributesResponse(QueryMemberAttributesResponse value) {
        return new JAXBElement<QueryMemberAttributesResponse>(_QueryMemberAttributesResponse_QNAME, QueryMemberAttributesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddMemberAttribute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/group_member/v2_1/local", name = "addMemberAttribute")
    public JAXBElement<AddMemberAttribute> createAddMemberAttribute(AddMemberAttribute value) {
        return new JAXBElement<AddMemberAttribute>(_AddMemberAttribute_QNAME, AddMemberAttribute.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryMemberAttributes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/group_member/v2_1/local", name = "queryMemberAttributes")
    public JAXBElement<QueryMemberAttributes> createQueryMemberAttributes(QueryMemberAttributes value) {
        return new JAXBElement<QueryMemberAttributes>(_QueryMemberAttributes_QNAME, QueryMemberAttributes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMemberAttribute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/group_member/v2_1/local", name = "deleteMemberAttribute")
    public JAXBElement<DeleteMemberAttribute> createDeleteMemberAttribute(DeleteMemberAttribute value) {
        return new JAXBElement<DeleteMemberAttribute>(_DeleteMemberAttribute_QNAME, DeleteMemberAttribute.class, null, value);
    }

}
